// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: portal.proto

package sitemessagesservice

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/portal-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAlertChannelsReq                = pb.AddAlertChannelsReq
	AddAlertChannelsResp               = pb.AddAlertChannelsResp
	AddAlertGroupLevelChannelsReq      = pb.AddAlertGroupLevelChannelsReq
	AddAlertGroupLevelChannelsResp     = pb.AddAlertGroupLevelChannelsResp
	AddAlertGroupMembersReq            = pb.AddAlertGroupMembersReq
	AddAlertGroupMembersResp           = pb.AddAlertGroupMembersResp
	AddAlertGroupsReq                  = pb.AddAlertGroupsReq
	AddAlertGroupsResp                 = pb.AddAlertGroupsResp
	AddGroupLevelChannelsReq           = pb.AddGroupLevelChannelsReq
	AddRAlertGroupUserReq              = pb.AddRAlertGroupUserReq
	AddSysAPIReq                       = pb.AddSysAPIReq
	AddSysAPIResp                      = pb.AddSysAPIResp
	AddSysDeptReq                      = pb.AddSysDeptReq
	AddSysDeptResp                     = pb.AddSysDeptResp
	AddSysMenuReq                      = pb.AddSysMenuReq
	AddSysMenuResp                     = pb.AddSysMenuResp
	AddSysRoleApiReq                   = pb.AddSysRoleApiReq
	AddSysRoleApiResp                  = pb.AddSysRoleApiResp
	AddSysRoleMenuReq                  = pb.AddSysRoleMenuReq
	AddSysRoleMenuResp                 = pb.AddSysRoleMenuResp
	AddSysRoleReq                      = pb.AddSysRoleReq
	AddSysRoleResp                     = pb.AddSysRoleResp
	AddSysTokenReq                     = pb.AddSysTokenReq
	AddSysTokenResp                    = pb.AddSysTokenResp
	AddSysUserReq                      = pb.AddSysUserReq
	AddSysUserResp                     = pb.AddSysUserResp
	AlertChannels                      = pb.AlertChannels
	AlertGroupLevelChannels            = pb.AlertGroupLevelChannels
	AlertGroupMembers                  = pb.AlertGroupMembers
	AlertGroups                        = pb.AlertGroups
	AlertNotifications                 = pb.AlertNotifications
	AlertNotifyReq                     = pb.AlertNotifyReq
	AlertNotifyResp                    = pb.AlertNotifyResp
	ApiAuthRequest                     = pb.ApiAuthRequest
	ApiAuthResponse                    = pb.ApiAuthResponse
	BatchDelAlertNotificationsReq      = pb.BatchDelAlertNotificationsReq
	BatchDelAlertNotificationsResp     = pb.BatchDelAlertNotificationsResp
	BatchDelSiteMessagesReq            = pb.BatchDelSiteMessagesReq
	BatchDelSiteMessagesResp           = pb.BatchDelSiteMessagesResp
	BatchReadSiteMessagesReq           = pb.BatchReadSiteMessagesReq
	BatchReadSiteMessagesResp          = pb.BatchReadSiteMessagesResp
	BindAlertGroupAppsReq              = pb.BindAlertGroupAppsReq
	BindAlertGroupAppsResp             = pb.BindAlertGroupAppsResp
	DelAlertChannelsReq                = pb.DelAlertChannelsReq
	DelAlertChannelsResp               = pb.DelAlertChannelsResp
	DelAlertGroupLevelChannelsReq      = pb.DelAlertGroupLevelChannelsReq
	DelAlertGroupLevelChannelsResp     = pb.DelAlertGroupLevelChannelsResp
	DelAlertGroupMembersReq            = pb.DelAlertGroupMembersReq
	DelAlertGroupMembersResp           = pb.DelAlertGroupMembersResp
	DelAlertGroupsReq                  = pb.DelAlertGroupsReq
	DelAlertGroupsResp                 = pb.DelAlertGroupsResp
	DelAlertNotificationsReq           = pb.DelAlertNotificationsReq
	DelAlertNotificationsResp          = pb.DelAlertNotificationsResp
	DelSiteMessagesReq                 = pb.DelSiteMessagesReq
	DelSiteMessagesResp                = pb.DelSiteMessagesResp
	DelSysAPIReq                       = pb.DelSysAPIReq
	DelSysAPIResp                      = pb.DelSysAPIResp
	DelSysDeptReq                      = pb.DelSysDeptReq
	DelSysDeptResp                     = pb.DelSysDeptResp
	DelSysLoginLogReq                  = pb.DelSysLoginLogReq
	DelSysLoginLogResp                 = pb.DelSysLoginLogResp
	DelSysMenuReq                      = pb.DelSysMenuReq
	DelSysMenuResp                     = pb.DelSysMenuResp
	DelSysRoleReq                      = pb.DelSysRoleReq
	DelSysRoleResp                     = pb.DelSysRoleResp
	DelSysTokenReq                     = pb.DelSysTokenReq
	DelSysTokenResp                    = pb.DelSysTokenResp
	DelSysUserReq                      = pb.DelSysUserReq
	DelSysUserResp                     = pb.DelSysUserResp
	GetAlertChannelsByIdReq            = pb.GetAlertChannelsByIdReq
	GetAlertChannelsByIdResp           = pb.GetAlertChannelsByIdResp
	GetAlertGroupLevelChannelsByIdReq  = pb.GetAlertGroupLevelChannelsByIdReq
	GetAlertGroupLevelChannelsByIdResp = pb.GetAlertGroupLevelChannelsByIdResp
	GetAlertGroupMembersByIdReq        = pb.GetAlertGroupMembersByIdReq
	GetAlertGroupMembersByIdResp       = pb.GetAlertGroupMembersByIdResp
	GetAlertGroupsByIdReq              = pb.GetAlertGroupsByIdReq
	GetAlertGroupsByIdResp             = pb.GetAlertGroupsByIdResp
	GetAlertNotificationsByIdReq       = pb.GetAlertNotificationsByIdReq
	GetAlertNotificationsByIdResp      = pb.GetAlertNotificationsByIdResp
	GetAllMenuTreeReq                  = pb.GetAllMenuTreeReq
	GetAllMenuTreeResp                 = pb.GetAllMenuTreeResp
	GetAllParentDeptReq                = pb.GetAllParentDeptReq
	GetAllParentDeptResp               = pb.GetAllParentDeptResp
	GetGroupsTreeReq                   = pb.GetGroupsTreeReq
	GetGroupsTreeResp                  = pb.GetGroupsTreeResp
	GetPlatformUrlReq                  = pb.GetPlatformUrlReq
	GetPlatformUrlResp                 = pb.GetPlatformUrlResp
	GetRolesMenuTreeReq                = pb.GetRolesMenuTreeReq
	GetRolesMenuTreeResp               = pb.GetRolesMenuTreeResp
	GetSiteMessagesByIdReq             = pb.GetSiteMessagesByIdReq
	GetSiteMessagesByIdResp            = pb.GetSiteMessagesByIdResp
	GetSiteMessagesCountReq            = pb.GetSiteMessagesCountReq
	GetSiteMessagesCountResp           = pb.GetSiteMessagesCountResp
	GetStorageUrlRequest               = pb.GetStorageUrlRequest
	GetStorageUrlResponse              = pb.GetStorageUrlResponse
	GetSysAPIByIdReq                   = pb.GetSysAPIByIdReq
	GetSysAPIByIdResp                  = pb.GetSysAPIByIdResp
	GetSysAPITreeReq                   = pb.GetSysAPITreeReq
	GetSysAPITreeResp                  = pb.GetSysAPITreeResp
	GetSysDeptByIdReq                  = pb.GetSysDeptByIdReq
	GetSysDeptByIdResp                 = pb.GetSysDeptByIdResp
	GetSysMenuByIdReq                  = pb.GetSysMenuByIdReq
	GetSysMenuByIdResp                 = pb.GetSysMenuByIdResp
	GetSysMenuListReq                  = pb.GetSysMenuListReq
	GetSysMenuListResp                 = pb.GetSysMenuListResp
	GetSysMenuSimpleTreeReq            = pb.GetSysMenuSimpleTreeReq
	GetSysMenuSimpleTreeResp           = pb.GetSysMenuSimpleTreeResp
	GetSysRoleByIdReq                  = pb.GetSysRoleByIdReq
	GetSysRoleByIdResp                 = pb.GetSysRoleByIdResp
	GetSysTokenByIdReq                 = pb.GetSysTokenByIdReq
	GetSysTokenByIdResp                = pb.GetSysTokenByIdResp
	GetSysTokenByUserIdReq             = pb.GetSysTokenByUserIdReq
	GetSysTokenByUserIdResp            = pb.GetSysTokenByUserIdResp
	GetSysUserByIdReq                  = pb.GetSysUserByIdReq
	GetSysUserByIdResp                 = pb.GetSysUserByIdResp
	GetSysUserInfoReq                  = pb.GetSysUserInfoReq
	GetSysUserInfoResp                 = pb.GetSysUserInfoResp
	GetTokenRequest                    = pb.GetTokenRequest
	GetTokenResponse                   = pb.GetTokenResponse
	GetUserUnreadMessagesReq           = pb.GetUserUnreadMessagesReq
	GetUserUnreadMessagesResp          = pb.GetUserUnreadMessagesResp
	GroupTreeNode                      = pb.GroupTreeNode
	LogoutRequest                      = pb.LogoutRequest
	LogoutResponse                     = pb.LogoutResponse
	RefreshTokenRequest                = pb.RefreshTokenRequest
	RefreshTokenResponse               = pb.RefreshTokenResponse
	ResetSysUserPwdReq                 = pb.ResetSysUserPwdReq
	ResetSysUserPwdResp                = pb.ResetSysUserPwdResp
	SearchAlertChannelsReq             = pb.SearchAlertChannelsReq
	SearchAlertChannelsResp            = pb.SearchAlertChannelsResp
	SearchAlertGroupAppsReq            = pb.SearchAlertGroupAppsReq
	SearchAlertGroupAppsResp           = pb.SearchAlertGroupAppsResp
	SearchAlertGroupLevelChannelsReq   = pb.SearchAlertGroupLevelChannelsReq
	SearchAlertGroupLevelChannelsResp  = pb.SearchAlertGroupLevelChannelsResp
	SearchAlertGroupMembersReq         = pb.SearchAlertGroupMembersReq
	SearchAlertGroupMembersResp        = pb.SearchAlertGroupMembersResp
	SearchAlertGroupsReq               = pb.SearchAlertGroupsReq
	SearchAlertGroupsResp              = pb.SearchAlertGroupsResp
	SearchAlertNotificationsReq        = pb.SearchAlertNotificationsReq
	SearchAlertNotificationsResp       = pb.SearchAlertNotificationsResp
	SearchSiteMessagesReq              = pb.SearchSiteMessagesReq
	SearchSiteMessagesResp             = pb.SearchSiteMessagesResp
	SearchSysAPIReq                    = pb.SearchSysAPIReq
	SearchSysAPIResp                   = pb.SearchSysAPIResp
	SearchSysDeptByParentIdReq         = pb.SearchSysDeptByParentIdReq
	SearchSysDeptByParentIdResp        = pb.SearchSysDeptByParentIdResp
	SearchSysDeptReq                   = pb.SearchSysDeptReq
	SearchSysDeptResp                  = pb.SearchSysDeptResp
	SearchSysLoginLogReq               = pb.SearchSysLoginLogReq
	SearchSysLoginLogResp              = pb.SearchSysLoginLogResp
	SearchSysMenuReq                   = pb.SearchSysMenuReq
	SearchSysMenuResp                  = pb.SearchSysMenuResp
	SearchSysRoleApiReq                = pb.SearchSysRoleApiReq
	SearchSysRoleApiResp               = pb.SearchSysRoleApiResp
	SearchSysRoleMenuReq               = pb.SearchSysRoleMenuReq
	SearchSysRoleMenuResp              = pb.SearchSysRoleMenuResp
	SearchSysRoleReq                   = pb.SearchSysRoleReq
	SearchSysRoleResp                  = pb.SearchSysRoleResp
	SearchSysTokenReq                  = pb.SearchSysTokenReq
	SearchSysTokenResp                 = pb.SearchSysTokenResp
	SearchSysUserReq                   = pb.SearchSysUserReq
	SearchSysUserResp                  = pb.SearchSysUserResp
	SearchSysUserRoleReq               = pb.SearchSysUserRoleReq
	SearchSysUserRoleResp              = pb.SearchSysUserRoleResp
	SetAllReadReq                      = pb.SetAllReadReq
	SetAllReadResp                     = pb.SetAllReadResp
	SiteMessages                       = pb.SiteMessages
	SysAPI                             = pb.SysAPI
	SysAPITreeNode                     = pb.SysAPITreeNode
	SysDept                            = pb.SysDept
	SysDeptTree                        = pb.SysDeptTree
	SysLoginLog                        = pb.SysLoginLog
	SysMenu                            = pb.SysMenu
	SysMenuSimpleTreeNode              = pb.SysMenuSimpleTreeNode
	SysMenuTree                        = pb.SysMenuTree
	SysRole                            = pb.SysRole
	SysToken                           = pb.SysToken
	SysUser                            = pb.SysUser
	TestLinkReq                        = pb.TestLinkReq
	TestLinkResp                       = pb.TestLinkResp
	TokenResponse                      = pb.TokenResponse
	UnbindAlertGroupAppsReq            = pb.UnbindAlertGroupAppsReq
	UnbindAlertGroupAppsResp           = pb.UnbindAlertGroupAppsResp
	UpdateAlertChannelsReq             = pb.UpdateAlertChannelsReq
	UpdateAlertChannelsResp            = pb.UpdateAlertChannelsResp
	UpdateAlertGroupLevelChannelsReq   = pb.UpdateAlertGroupLevelChannelsReq
	UpdateAlertGroupLevelChannelsResp  = pb.UpdateAlertGroupLevelChannelsResp
	UpdateAlertGroupMembersReq         = pb.UpdateAlertGroupMembersReq
	UpdateAlertGroupMembersResp        = pb.UpdateAlertGroupMembersResp
	UpdateAlertGroupsReq               = pb.UpdateAlertGroupsReq
	UpdateAlertGroupsResp              = pb.UpdateAlertGroupsResp
	UpdateSysAPIReq                    = pb.UpdateSysAPIReq
	UpdateSysAPIResp                   = pb.UpdateSysAPIResp
	UpdateSysDeptReq                   = pb.UpdateSysDeptReq
	UpdateSysDeptResp                  = pb.UpdateSysDeptResp
	UpdateSysMenuReq                   = pb.UpdateSysMenuReq
	UpdateSysMenuResp                  = pb.UpdateSysMenuResp
	UpdateSysRoleReq                   = pb.UpdateSysRoleReq
	UpdateSysRoleResp                  = pb.UpdateSysRoleResp
	UpdateSysUserAvatarReq             = pb.UpdateSysUserAvatarReq
	UpdateSysUserAvatarResp            = pb.UpdateSysUserAvatarResp
	UpdateSysUserBindRoleReq           = pb.UpdateSysUserBindRoleReq
	UpdateSysUserBindRoleResp          = pb.UpdateSysUserBindRoleResp
	UpdateSysUserInfoReq               = pb.UpdateSysUserInfoReq
	UpdateSysUserInfoResp              = pb.UpdateSysUserInfoResp
	UpdateSysUserPwdReq                = pb.UpdateSysUserPwdReq
	UpdateSysUserPwdResp               = pb.UpdateSysUserPwdResp
	UpdateSysUserReq                   = pb.UpdateSysUserReq
	UpdateSysUserResp                  = pb.UpdateSysUserResp
	UpdateSysUserStatusReq             = pb.UpdateSysUserStatusReq
	UpdateSysUserStatusResp            = pb.UpdateSysUserStatusResp
	UploadImageRequest                 = pb.UploadImageRequest
	UploadImageResponse                = pb.UploadImageResponse
	VerifyTokenRequest                 = pb.VerifyTokenRequest
	VerifyTokenResponse                = pb.VerifyTokenResponse

	SiteMessagesService interface {
		// -----------------------站内信表-----------------------
		SiteMessagesDel(ctx context.Context, in *DelSiteMessagesReq, opts ...grpc.CallOption) (*DelSiteMessagesResp, error)
		SiteMessagesByIdGet(ctx context.Context, in *GetSiteMessagesByIdReq, opts ...grpc.CallOption) (*GetSiteMessagesByIdResp, error)
		SiteMessagesSearch(ctx context.Context, in *SearchSiteMessagesReq, opts ...grpc.CallOption) (*SearchSiteMessagesResp, error)
		// 设置全部已读
		SiteMessagesSetAllRead(ctx context.Context, in *SetAllReadReq, opts ...grpc.CallOption) (*SetAllReadResp, error)
		// 批量删除
		SiteMessagesBatchDel(ctx context.Context, in *BatchDelSiteMessagesReq, opts ...grpc.CallOption) (*BatchDelSiteMessagesResp, error)
		// 批量已读
		SiteMessagesBatchRead(ctx context.Context, in *BatchReadSiteMessagesReq, opts ...grpc.CallOption) (*BatchReadSiteMessagesResp, error)
		// 获取某用户所有站内消息数量和 已读数量 和 未读数量
		SiteMessagesCount(ctx context.Context, in *GetSiteMessagesCountReq, opts ...grpc.CallOption) (*GetSiteMessagesCountResp, error)
		GetUserUnreadMessages(ctx context.Context, in *GetUserUnreadMessagesReq, opts ...grpc.CallOption) (*GetUserUnreadMessagesResp, error)
	}

	defaultSiteMessagesService struct {
		cli zrpc.Client
	}
)

func NewSiteMessagesService(cli zrpc.Client) SiteMessagesService {
	return &defaultSiteMessagesService{
		cli: cli,
	}
}

// -----------------------站内信表-----------------------
func (m *defaultSiteMessagesService) SiteMessagesDel(ctx context.Context, in *DelSiteMessagesReq, opts ...grpc.CallOption) (*DelSiteMessagesResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesDel(ctx, in, opts...)
}

func (m *defaultSiteMessagesService) SiteMessagesByIdGet(ctx context.Context, in *GetSiteMessagesByIdReq, opts ...grpc.CallOption) (*GetSiteMessagesByIdResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesByIdGet(ctx, in, opts...)
}

func (m *defaultSiteMessagesService) SiteMessagesSearch(ctx context.Context, in *SearchSiteMessagesReq, opts ...grpc.CallOption) (*SearchSiteMessagesResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesSearch(ctx, in, opts...)
}

// 设置全部已读
func (m *defaultSiteMessagesService) SiteMessagesSetAllRead(ctx context.Context, in *SetAllReadReq, opts ...grpc.CallOption) (*SetAllReadResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesSetAllRead(ctx, in, opts...)
}

// 批量删除
func (m *defaultSiteMessagesService) SiteMessagesBatchDel(ctx context.Context, in *BatchDelSiteMessagesReq, opts ...grpc.CallOption) (*BatchDelSiteMessagesResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesBatchDel(ctx, in, opts...)
}

// 批量已读
func (m *defaultSiteMessagesService) SiteMessagesBatchRead(ctx context.Context, in *BatchReadSiteMessagesReq, opts ...grpc.CallOption) (*BatchReadSiteMessagesResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesBatchRead(ctx, in, opts...)
}

// 获取某用户所有站内消息数量和 已读数量 和 未读数量
func (m *defaultSiteMessagesService) SiteMessagesCount(ctx context.Context, in *GetSiteMessagesCountReq, opts ...grpc.CallOption) (*GetSiteMessagesCountResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.SiteMessagesCount(ctx, in, opts...)
}

func (m *defaultSiteMessagesService) GetUserUnreadMessages(ctx context.Context, in *GetUserUnreadMessagesReq, opts ...grpc.CallOption) (*GetUserUnreadMessagesResp, error) {
	client := pb.NewSiteMessagesServiceClient(m.cli.Conn())
	return client.GetUserUnreadMessages(ctx, in, opts...)
}
