// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: portal.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/portal-rpc/internal/logic/portalservice"
	"github.com/yanshicheng/kube-nova/application/portal-rpc/internal/svc"
	"github.com/yanshicheng/kube-nova/application/portal-rpc/pb"
)

type PortalServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPortalServiceServer
}

func NewPortalServiceServer(svcCtx *svc.ServiceContext) *PortalServiceServer {
	return &PortalServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------系统平台表-----------------------
func (s *PortalServiceServer) PlatformAdd(ctx context.Context, in *pb.AddSysPlatformReq) (*pb.AddSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformAddLogic(ctx, s.svcCtx)
	return l.PlatformAdd(in)
}

func (s *PortalServiceServer) PlatformUpdate(ctx context.Context, in *pb.UpdateSysPlatformReq) (*pb.UpdateSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformUpdateLogic(ctx, s.svcCtx)
	return l.PlatformUpdate(in)
}

func (s *PortalServiceServer) PlatformDel(ctx context.Context, in *pb.DelSysPlatformReq) (*pb.DelSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformDelLogic(ctx, s.svcCtx)
	return l.PlatformDel(in)
}

func (s *PortalServiceServer) PlatformGetById(ctx context.Context, in *pb.GetSysPlatformByIdReq) (*pb.GetSysPlatformByIdResp, error) {
	l := portalservicelogic.NewPlatformGetByIdLogic(ctx, s.svcCtx)
	return l.PlatformGetById(in)
}

func (s *PortalServiceServer) PlatformSearch(ctx context.Context, in *pb.SearchSysPlatformReq) (*pb.SearchSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformSearchLogic(ctx, s.svcCtx)
	return l.PlatformSearch(in)
}

// 快捷操作
func (s *PortalServiceServer) PlatformEnable(ctx context.Context, in *pb.EnableSysPlatformReq) (*pb.EnableSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformEnableLogic(ctx, s.svcCtx)
	return l.PlatformEnable(in)
}

func (s *PortalServiceServer) PlatformDisable(ctx context.Context, in *pb.DisableSysPlatformReq) (*pb.DisableSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformDisableLogic(ctx, s.svcCtx)
	return l.PlatformDisable(in)
}

func (s *PortalServiceServer) PlatformSetDefault(ctx context.Context, in *pb.SetDefaultSysPlatformReq) (*pb.SetDefaultSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformSetDefaultLogic(ctx, s.svcCtx)
	return l.PlatformSetDefault(in)
}

func (s *PortalServiceServer) PlatformUnsetDefault(ctx context.Context, in *pb.UnsetDefaultSysPlatformReq) (*pb.UnsetDefaultSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformUnsetDefaultLogic(ctx, s.svcCtx)
	return l.PlatformUnsetDefault(in)
}

func (s *PortalServiceServer) PlatformGetDefault(ctx context.Context, in *pb.GetDefaultSysPlatformReq) (*pb.GetDefaultSysPlatformResp, error) {
	l := portalservicelogic.NewPlatformGetDefaultLogic(ctx, s.svcCtx)
	return l.PlatformGetDefault(in)
}

func (s *PortalServiceServer) PlatformGetAllEnabled(ctx context.Context, in *pb.GetAllEnabledPlatformsReq) (*pb.GetAllEnabledPlatformsResp, error) {
	l := portalservicelogic.NewPlatformGetAllEnabledLogic(ctx, s.svcCtx)
	return l.PlatformGetAllEnabled(in)
}

// -----------------------用户平台权限表-----------------------
func (s *PortalServiceServer) UserPlatformBind(ctx context.Context, in *pb.BindUserPlatformReq) (*pb.BindUserPlatformResp, error) {
	l := portalservicelogic.NewUserPlatformBindLogic(ctx, s.svcCtx)
	return l.UserPlatformBind(in)
}

func (s *PortalServiceServer) UserPlatformUnbind(ctx context.Context, in *pb.UnbindUserPlatformReq) (*pb.UnbindUserPlatformResp, error) {
	l := portalservicelogic.NewUserPlatformUnbindLogic(ctx, s.svcCtx)
	return l.UserPlatformUnbind(in)
}

func (s *PortalServiceServer) UserPlatformGet(ctx context.Context, in *pb.GetUserPlatformsReq) (*pb.GetUserPlatformsResp, error) {
	l := portalservicelogic.NewUserPlatformGetLogic(ctx, s.svcCtx)
	return l.UserPlatformGet(in)
}

func (s *PortalServiceServer) PlatformUsersGet(ctx context.Context, in *pb.GetPlatformUsersReq) (*pb.GetPlatformUsersResp, error) {
	l := portalservicelogic.NewPlatformUsersGetLogic(ctx, s.svcCtx)
	return l.PlatformUsersGet(in)
}

// -----------------------系统API权限表-----------------------
func (s *PortalServiceServer) APIAdd(ctx context.Context, in *pb.AddSysAPIReq) (*pb.AddSysAPIResp, error) {
	l := portalservicelogic.NewAPIAddLogic(ctx, s.svcCtx)
	return l.APIAdd(in)
}

func (s *PortalServiceServer) APIUpdate(ctx context.Context, in *pb.UpdateSysAPIReq) (*pb.UpdateSysAPIResp, error) {
	l := portalservicelogic.NewAPIUpdateLogic(ctx, s.svcCtx)
	return l.APIUpdate(in)
}

func (s *PortalServiceServer) APIDel(ctx context.Context, in *pb.DelSysAPIReq) (*pb.DelSysAPIResp, error) {
	l := portalservicelogic.NewAPIDelLogic(ctx, s.svcCtx)
	return l.APIDel(in)
}

func (s *PortalServiceServer) APIGetById(ctx context.Context, in *pb.GetSysAPIByIdReq) (*pb.GetSysAPIByIdResp, error) {
	l := portalservicelogic.NewAPIGetByIdLogic(ctx, s.svcCtx)
	return l.APIGetById(in)
}

func (s *PortalServiceServer) APISearch(ctx context.Context, in *pb.SearchSysAPIReq) (*pb.SearchSysAPIResp, error) {
	l := portalservicelogic.NewAPISearchLogic(ctx, s.svcCtx)
	return l.APISearch(in)
}

// 获取所有分组树状数据(仅包含id,name,pid，平铺形式)
func (s *PortalServiceServer) APIGetGroupsTree(ctx context.Context, in *pb.GetGroupsTreeReq) (*pb.GetGroupsTreeResp, error) {
	l := portalservicelogic.NewAPIGetGroupsTreeLogic(ctx, s.svcCtx)
	return l.APIGetGroupsTree(in)
}

func (s *PortalServiceServer) APIGetTree(ctx context.Context, in *pb.GetSysAPITreeReq) (*pb.GetSysAPITreeResp, error) {
	l := portalservicelogic.NewAPIGetTreeLogic(ctx, s.svcCtx)
	return l.APIGetTree(in)
}

// -----------------------部门表-----------------------
func (s *PortalServiceServer) DeptAdd(ctx context.Context, in *pb.AddSysDeptReq) (*pb.AddSysDeptResp, error) {
	l := portalservicelogic.NewDeptAddLogic(ctx, s.svcCtx)
	return l.DeptAdd(in)
}

func (s *PortalServiceServer) DeptUpdate(ctx context.Context, in *pb.UpdateSysDeptReq) (*pb.UpdateSysDeptResp, error) {
	l := portalservicelogic.NewDeptUpdateLogic(ctx, s.svcCtx)
	return l.DeptUpdate(in)
}

func (s *PortalServiceServer) DeptDel(ctx context.Context, in *pb.DelSysDeptReq) (*pb.DelSysDeptResp, error) {
	l := portalservicelogic.NewDeptDelLogic(ctx, s.svcCtx)
	return l.DeptDel(in)
}

func (s *PortalServiceServer) DeptGetById(ctx context.Context, in *pb.GetSysDeptByIdReq) (*pb.GetSysDeptByIdResp, error) {
	l := portalservicelogic.NewDeptGetByIdLogic(ctx, s.svcCtx)
	return l.DeptGetById(in)
}

func (s *PortalServiceServer) DeptSearch(ctx context.Context, in *pb.SearchSysDeptReq) (*pb.SearchSysDeptResp, error) {
	l := portalservicelogic.NewDeptSearchLogic(ctx, s.svcCtx)
	return l.DeptSearch(in)
}

// 根据 父id 查询 下一级 部门
func (s *PortalServiceServer) DeptGetNextLevel(ctx context.Context, in *pb.SearchSysDeptByParentIdReq) (*pb.SearchSysDeptByParentIdResp, error) {
	l := portalservicelogic.NewDeptGetNextLevelLogic(ctx, s.svcCtx)
	return l.DeptGetNextLevel(in)
}

// 查询所有父级 部门
func (s *PortalServiceServer) DeptGetAllParent(ctx context.Context, in *pb.GetAllParentDeptReq) (*pb.GetAllParentDeptResp, error) {
	l := portalservicelogic.NewDeptGetAllParentLogic(ctx, s.svcCtx)
	return l.DeptGetAllParent(in)
}

// -----------------------登录日志表-----------------------
func (s *PortalServiceServer) LoginLogDel(ctx context.Context, in *pb.DelSysLoginLogReq) (*pb.DelSysLoginLogResp, error) {
	l := portalservicelogic.NewLoginLogDelLogic(ctx, s.svcCtx)
	return l.LoginLogDel(in)
}

func (s *PortalServiceServer) LoginLogSearch(ctx context.Context, in *pb.SearchSysLoginLogReq) (*pb.SearchSysLoginLogResp, error) {
	l := portalservicelogic.NewLoginLogSearchLogic(ctx, s.svcCtx)
	return l.LoginLogSearch(in)
}

// -----------------------角色表-----------------------
func (s *PortalServiceServer) RoleAdd(ctx context.Context, in *pb.AddSysRoleReq) (*pb.AddSysRoleResp, error) {
	l := portalservicelogic.NewRoleAddLogic(ctx, s.svcCtx)
	return l.RoleAdd(in)
}

func (s *PortalServiceServer) RoleUpdate(ctx context.Context, in *pb.UpdateSysRoleReq) (*pb.UpdateSysRoleResp, error) {
	l := portalservicelogic.NewRoleUpdateLogic(ctx, s.svcCtx)
	return l.RoleUpdate(in)
}

func (s *PortalServiceServer) RoleDel(ctx context.Context, in *pb.DelSysRoleReq) (*pb.DelSysRoleResp, error) {
	l := portalservicelogic.NewRoleDelLogic(ctx, s.svcCtx)
	return l.RoleDel(in)
}

func (s *PortalServiceServer) RoleGetById(ctx context.Context, in *pb.GetSysRoleByIdReq) (*pb.GetSysRoleByIdResp, error) {
	l := portalservicelogic.NewRoleGetByIdLogic(ctx, s.svcCtx)
	return l.RoleGetById(in)
}

func (s *PortalServiceServer) RoleSearch(ctx context.Context, in *pb.SearchSysRoleReq) (*pb.SearchSysRoleResp, error) {
	l := portalservicelogic.NewRoleSearchLogic(ctx, s.svcCtx)
	return l.RoleSearch(in)
}

// 角色菜单关联方法
func (s *PortalServiceServer) RoleAddMenu(ctx context.Context, in *pb.AddSysRoleMenuReq) (*pb.AddSysRoleMenuResp, error) {
	l := portalservicelogic.NewRoleAddMenuLogic(ctx, s.svcCtx)
	return l.RoleAddMenu(in)
}

// 查询关联了哪些菜单
func (s *PortalServiceServer) RoleSearchMenu(ctx context.Context, in *pb.SearchSysRoleMenuReq) (*pb.SearchSysRoleMenuResp, error) {
	l := portalservicelogic.NewRoleSearchMenuLogic(ctx, s.svcCtx)
	return l.RoleSearchMenu(in)
}

// 角色 api权限关联方法
func (s *PortalServiceServer) RoleAddApi(ctx context.Context, in *pb.AddSysRoleApiReq) (*pb.AddSysRoleApiResp, error) {
	l := portalservicelogic.NewRoleAddApiLogic(ctx, s.svcCtx)
	return l.RoleAddApi(in)
}

// 查询关联了哪些 api权限
func (s *PortalServiceServer) RoleSearchApi(ctx context.Context, in *pb.SearchSysRoleApiReq) (*pb.SearchSysRoleApiResp, error) {
	l := portalservicelogic.NewRoleSearchApiLogic(ctx, s.svcCtx)
	return l.RoleSearchApi(in)
}

// -----------------------API Token表-----------------------
func (s *PortalServiceServer) TokenAdd(ctx context.Context, in *pb.AddSysTokenReq) (*pb.AddSysTokenResp, error) {
	l := portalservicelogic.NewTokenAddLogic(ctx, s.svcCtx)
	return l.TokenAdd(in)
}

func (s *PortalServiceServer) TokenDel(ctx context.Context, in *pb.DelSysTokenReq) (*pb.DelSysTokenResp, error) {
	l := portalservicelogic.NewTokenDelLogic(ctx, s.svcCtx)
	return l.TokenDel(in)
}

func (s *PortalServiceServer) TokenGetById(ctx context.Context, in *pb.GetSysTokenByIdReq) (*pb.GetSysTokenByIdResp, error) {
	l := portalservicelogic.NewTokenGetByIdLogic(ctx, s.svcCtx)
	return l.TokenGetById(in)
}

func (s *PortalServiceServer) TokenSearch(ctx context.Context, in *pb.SearchSysTokenReq) (*pb.SearchSysTokenResp, error) {
	l := portalservicelogic.NewTokenSearchLogic(ctx, s.svcCtx)
	return l.TokenSearch(in)
}

// 获取某个用户token 方法
func (s *PortalServiceServer) TokenGetByUserId(ctx context.Context, in *pb.GetSysTokenByUserIdReq) (*pb.GetSysTokenByUserIdResp, error) {
	l := portalservicelogic.NewTokenGetByUserIdLogic(ctx, s.svcCtx)
	return l.TokenGetByUserId(in)
}

// -----------------------用户表-----------------------
func (s *PortalServiceServer) UserAdd(ctx context.Context, in *pb.AddSysUserReq) (*pb.AddSysUserResp, error) {
	l := portalservicelogic.NewUserAddLogic(ctx, s.svcCtx)
	return l.UserAdd(in)
}

func (s *PortalServiceServer) UserUpdate(ctx context.Context, in *pb.UpdateSysUserReq) (*pb.UpdateSysUserResp, error) {
	l := portalservicelogic.NewUserUpdateLogic(ctx, s.svcCtx)
	return l.UserUpdate(in)
}

func (s *PortalServiceServer) UserDel(ctx context.Context, in *pb.DelSysUserReq) (*pb.DelSysUserResp, error) {
	l := portalservicelogic.NewUserDelLogic(ctx, s.svcCtx)
	return l.UserDel(in)
}

func (s *PortalServiceServer) UserGetById(ctx context.Context, in *pb.GetSysUserByIdReq) (*pb.GetSysUserByIdResp, error) {
	l := portalservicelogic.NewUserGetByIdLogic(ctx, s.svcCtx)
	return l.UserGetById(in)
}

func (s *PortalServiceServer) UserSearch(ctx context.Context, in *pb.SearchSysUserReq) (*pb.SearchSysUserResp, error) {
	l := portalservicelogic.NewUserSearchLogic(ctx, s.svcCtx)
	return l.UserSearch(in)
}

// 通过用户ID 查询用户角色列表
func (s *PortalServiceServer) UserSearchRole(ctx context.Context, in *pb.SearchSysUserRoleReq) (*pb.SearchSysUserRoleResp, error) {
	l := portalservicelogic.NewUserSearchRoleLogic(ctx, s.svcCtx)
	return l.UserSearchRole(in)
}

// 个人修改信息
func (s *PortalServiceServer) UserUpdateInfo(ctx context.Context, in *pb.UpdateSysUserInfoReq) (*pb.UpdateSysUserInfoResp, error) {
	l := portalservicelogic.NewUserUpdateInfoLogic(ctx, s.svcCtx)
	return l.UserUpdateInfo(in)
}

// 修改头像
func (s *PortalServiceServer) UserUpdateAvatar(ctx context.Context, in *pb.UpdateSysUserAvatarReq) (*pb.UpdateSysUserAvatarResp, error) {
	l := portalservicelogic.NewUserUpdateAvatarLogic(ctx, s.svcCtx)
	return l.UserUpdateAvatar(in)
}

// 修改密码
func (s *PortalServiceServer) UserUpdatePwd(ctx context.Context, in *pb.UpdateSysUserPwdReq) (*pb.UpdateSysUserPwdResp, error) {
	l := portalservicelogic.NewUserUpdatePwdLogic(ctx, s.svcCtx)
	return l.UserUpdatePwd(in)
}

// 禁用或启用用户
func (s *PortalServiceServer) UserUpdateStatus(ctx context.Context, in *pb.UpdateSysUserStatusReq) (*pb.UpdateSysUserStatusResp, error) {
	l := portalservicelogic.NewUserUpdateStatusLogic(ctx, s.svcCtx)
	return l.UserUpdateStatus(in)
}

// 用户绑定角色
func (s *PortalServiceServer) UserUpdateBindRole(ctx context.Context, in *pb.UpdateSysUserBindRoleReq) (*pb.UpdateSysUserBindRoleResp, error) {
	l := portalservicelogic.NewUserUpdateBindRoleLogic(ctx, s.svcCtx)
	return l.UserUpdateBindRole(in)
}

// 用户个人详情
func (s *PortalServiceServer) UserGetInfo(ctx context.Context, in *pb.GetSysUserInfoReq) (*pb.GetSysUserInfoResp, error) {
	l := portalservicelogic.NewUserGetInfoLogic(ctx, s.svcCtx)
	return l.UserGetInfo(in)
}

// 重置密码
func (s *PortalServiceServer) UserResetPwd(ctx context.Context, in *pb.ResetSysUserPwdReq) (*pb.ResetSysUserPwdResp, error) {
	l := portalservicelogic.NewUserResetPwdLogic(ctx, s.svcCtx)
	return l.UserResetPwd(in)
}

// -----------------------系统菜单表-----------------------
func (s *PortalServiceServer) MenuAdd(ctx context.Context, in *pb.AddSysMenuReq) (*pb.AddSysMenuResp, error) {
	l := portalservicelogic.NewMenuAddLogic(ctx, s.svcCtx)
	return l.MenuAdd(in)
}

func (s *PortalServiceServer) MenuUpdate(ctx context.Context, in *pb.UpdateSysMenuReq) (*pb.UpdateSysMenuResp, error) {
	l := portalservicelogic.NewMenuUpdateLogic(ctx, s.svcCtx)
	return l.MenuUpdate(in)
}

func (s *PortalServiceServer) MenuDel(ctx context.Context, in *pb.DelSysMenuReq) (*pb.DelSysMenuResp, error) {
	l := portalservicelogic.NewMenuDelLogic(ctx, s.svcCtx)
	return l.MenuDel(in)
}

func (s *PortalServiceServer) MenuGetById(ctx context.Context, in *pb.GetSysMenuByIdReq) (*pb.GetSysMenuByIdResp, error) {
	l := portalservicelogic.NewMenuGetByIdLogic(ctx, s.svcCtx)
	return l.MenuGetById(in)
}

// 搜索和列表操作
func (s *PortalServiceServer) MenuSearch(ctx context.Context, in *pb.SearchSysMenuReq) (*pb.SearchSysMenuResp, error) {
	l := portalservicelogic.NewMenuSearchLogic(ctx, s.svcCtx)
	return l.MenuSearch(in)
}

func (s *PortalServiceServer) MenuGetList(ctx context.Context, in *pb.GetSysMenuListReq) (*pb.GetSysMenuListResp, error) {
	l := portalservicelogic.NewMenuGetListLogic(ctx, s.svcCtx)
	return l.MenuGetList(in)
}

// 树状结构操作
func (s *PortalServiceServer) MenuGetRolesMenuTree(ctx context.Context, in *pb.GetRolesMenuTreeReq) (*pb.GetRolesMenuTreeResp, error) {
	l := portalservicelogic.NewMenuGetRolesMenuTreeLogic(ctx, s.svcCtx)
	return l.MenuGetRolesMenuTree(in)
}

func (s *PortalServiceServer) MenuGetAllMenuTree(ctx context.Context, in *pb.GetAllMenuTreeReq) (*pb.GetAllMenuTreeResp, error) {
	l := portalservicelogic.NewMenuGetAllMenuTreeLogic(ctx, s.svcCtx)
	return l.MenuGetAllMenuTree(in)
}

func (s *PortalServiceServer) MenuGetSimpleTree(ctx context.Context, in *pb.GetSysMenuSimpleTreeReq) (*pb.GetSysMenuSimpleTreeResp, error) {
	l := portalservicelogic.NewMenuGetSimpleTreeLogic(ctx, s.svcCtx)
	return l.MenuGetSimpleTree(in)
}

// 获取平台地址
func (s *PortalServiceServer) GetKubeNovaPlatformUrl(ctx context.Context, in *pb.GetPlatformUrlReq) (*pb.GetPlatformUrlResp, error) {
	l := portalservicelogic.NewGetKubeNovaPlatformUrlLogic(ctx, s.svcCtx)
	return l.GetKubeNovaPlatformUrl(in)
}
