---
apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-rpc
  namespace: kube-nova
spec:
  selector:
    app: devops-pipeline-rpc
  ports:
    - port: 30032
      targetPort: 30032
  type: ClusterIP
