// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	alertGroupsFieldNames          = builder.RawFieldNames(&AlertGroups{})
	alertGroupsRows                = strings.Join(alertGroupsFieldNames, ",")
	alertGroupsRowsExpectAutoSet   = strings.Join(stringx.Remove(alertGroupsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	alertGroupsRowsWithPlaceHolder = strings.Join(stringx.Remove(alertGroupsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsAlertGroupsIdPrefix   = "cache:ikubeops:alertGroups:id:"
	cacheIkubeopsAlertGroupsUuidPrefix = "cache:ikubeops:alertGroups:uuid:"
)

type (
	alertGroupsModel interface {
		Insert(ctx context.Context, data *AlertGroups) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*AlertGroups, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*AlertGroups, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*AlertGroups, error)
		FindOneByUuid(ctx context.Context, uuid string) (*AlertGroups, error)
		Update(ctx context.Context, data *AlertGroups) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultAlertGroupsModel struct {
		sqlc.CachedConn
		table string
	}

	AlertGroups struct {
		Id           uint64    `db:"id"`            // 主键ID
		Uuid         string    `db:"uuid"`          // 告警组UUID
		GroupName    string    `db:"group_name"`    // 告警组名称
		GroupType    string    `db:"group_type"`    // 组类型(normal=普通, duty=值班)
		Description  string    `db:"description"`   // 告警组描述
		FilterRules  string    `db:"filter_rules"`  // 告警过滤规则(标签匹配规则)
		DutySchedule string    `db:"duty_schedule"` // 值班排班表(仅duty类型有效,格式:{"schedule":[{"day":"Monday","user_ids":[1,2]}]})
		SortOrder    uint64    `db:"sort_order"`    // 排序序号
		CreatedBy    string    `db:"created_by"`    // 创建人
		UpdatedBy    string    `db:"updated_by"`    // 更新人
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
		IsDeleted    int64     `db:"is_deleted"`    // 是否删除
	}
)

func newAlertGroupsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAlertGroupsModel {
	return &defaultAlertGroupsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`alert_groups`",
	}
}

func (m *defaultAlertGroupsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, id)
	ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, data.Uuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsAlertGroupsIdKey, ikubeopsAlertGroupsUuidKey)
	return err
}

func (m *defaultAlertGroupsModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, id)
	ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, data.Uuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsAlertGroupsIdKey, ikubeopsAlertGroupsUuidKey)
	return err
}

func (m *defaultAlertGroupsModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultAlertGroupsModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, id)
		ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, data.Uuid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsAlertGroupsIdKey, ikubeopsAlertGroupsUuidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultAlertGroupsModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, id)
		ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, data.Uuid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsAlertGroupsIdKey, ikubeopsAlertGroupsUuidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultAlertGroupsModel) FindOne(ctx context.Context, id uint64) (*AlertGroups, error) {
	ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, id)
	var resp AlertGroups
	err := m.QueryRowCtx(ctx, &resp, ikubeopsAlertGroupsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", alertGroupsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAlertGroupsModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*AlertGroups, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*AlertGroups
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", alertGroupsRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultAlertGroupsModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*AlertGroups, error) {
	// 处理 nil 参数
	if args == nil {
		args = []any{}
	}
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", alertGroupsRows, m.table, where, orderStr)
	var resp []*AlertGroups
	// 根据是否有参数来调用
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultAlertGroupsModel) FindOneByUuid(ctx context.Context, uuid string) (*AlertGroups, error) {
	ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, uuid)
	var resp AlertGroups
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsAlertGroupsUuidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `uuid` = ? AND `is_deleted` = 0  limit 1", alertGroupsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uuid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAlertGroupsModel) Insert(ctx context.Context, data *AlertGroups) (sql.Result, error) {
	ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, data.Id)
	ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, data.Uuid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, alertGroupsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uuid, data.GroupName, data.GroupType, data.Description, data.FilterRules, data.DutySchedule, data.SortOrder, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, ikubeopsAlertGroupsIdKey, ikubeopsAlertGroupsUuidKey)
	return ret, err
}

func (m *defaultAlertGroupsModel) Update(ctx context.Context, newData *AlertGroups) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsAlertGroupsIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, data.Id)
	ikubeopsAlertGroupsUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsUuidPrefix, data.Uuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, alertGroupsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Uuid, newData.GroupName, newData.GroupType, newData.Description, newData.FilterRules, newData.DutySchedule, newData.SortOrder, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, ikubeopsAlertGroupsIdKey, ikubeopsAlertGroupsUuidKey)
	return err
}

func (m *defaultAlertGroupsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsAlertGroupsIdPrefix, primary)
}

func (m *defaultAlertGroupsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", alertGroupsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAlertGroupsModel) tableName() string {
	return m.table
}
