// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysMenuFieldNames          = builder.RawFieldNames(&SysMenu{})
	sysMenuRows                = strings.Join(sysMenuFieldNames, ",")
	sysMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(sysMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(sysMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaSysMenuIdPrefix   = "cache:kubeNova:sysMenu:id:"
	cacheKubeNovaSysMenuNamePrefix = "cache:kubeNova:sysMenu:name:"
)

type (
	sysMenuModel interface {
		Insert(ctx context.Context, data *SysMenu) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SysMenu, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysMenu, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysMenu, error)
		FindOneByName(ctx context.Context, name string) (*SysMenu, error)
		Update(ctx context.Context, data *SysMenu) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultSysMenuModel struct {
		sqlc.CachedConn
		table string
	}

	SysMenu struct {
		Id            uint64         `db:"id"`              // 自增主键
		ParentId      uint64         `db:"parent_id"`       // 父菜单ID，顶级菜单为0
		PlatformId    uint64         `db:"platform_id"`     // 平台ID（关联sys_platform表，默认1为容器平台）
		MenuType      int64          `db:"menu_type"`       // 菜单类型（1目录 2菜单 3按钮）
		Name          string         `db:"name"`            // 菜单名称（路由name）
		Path          string         `db:"path"`            // 路由地址
		Component     string         `db:"component"`       // 组件路径
		Redirect      string         `db:"redirect"`        // 重定向地址
		Label         string         `db:"label"`           // 权限标识
		Title         string         `db:"title"`           // 菜单标题（meta.title）
		Icon          string         `db:"icon"`            // 菜单图标
		Sort          int64          `db:"sort"`            // 排序
		Link          string         `db:"link"`            // 外部链接/内嵌地址
		IsEnable      int64          `db:"is_enable"`       // 是否启用（0否 1是）
		IsMenu        int64          `db:"is_menu"`         // 是否为菜单（0否 1是）
		KeepAlive     int64          `db:"keep_alive"`      // 页面缓存（0否 1是）
		IsHide        int64          `db:"is_hide"`         // 是否隐藏（0否 1是）
		IsIframe      int64          `db:"is_iframe"`       // 是否内嵌（0否 1是）
		IsHideTab     int64          `db:"is_hide_tab"`     // 是否在标签页中隐藏（0否 1是）
		ShowBadge     int64          `db:"show_badge"`      // 是否显示徽章（0否 1是）
		ShowTextBadge string         `db:"show_text_badge"` // 文本徽章内容
		IsFirstLevel  int64          `db:"is_first_level"`  // 是否为一级菜单（0否 1是）
		FixedTab      int64          `db:"fixed_tab"`       // 是否固定标签页（0否 1是）
		IsFullPage    int64          `db:"is_full_page"`    // 是否为全屏页面（0否 1是）
		ActivePath    string         `db:"active_path"`     // 激活菜单路径
		Roles         sql.NullString `db:"roles"`           // 角色权限（JSON格式存储数组）
		AuthName      string         `db:"auth_name"`       // 按钮权限名称
		AuthLabel     string         `db:"auth_label"`      // 按钮权限标识
		AuthIcon      string         `db:"auth_icon"`       // 按钮图标
		AuthSort      int64          `db:"auth_sort"`       // 按钮权限排序
		Status        int64          `db:"status"`          // 状态（0停用 1启用）
		IsDeleted     int64          `db:"is_deleted"`      // 是否删除（true: 删除， false: 正常）
		CreateTime    time.Time      `db:"create_time"`     // 创建时间
		UpdateTime    time.Time      `db:"update_time"`     // 更新时间
		CreateBy      string         `db:"create_by"`       // 创建人
		UpdateBy      string         `db:"update_by"`       // 更新人
	}
)

func newSysMenuModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysMenuModel {
	return &defaultSysMenuModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_menu`",
	}
}

func (m *defaultSysMenuModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, id)
	kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaSysMenuIdKey, kubeNovaSysMenuNameKey)
	return err
}

func (m *defaultSysMenuModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, id)
	kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaSysMenuIdKey, kubeNovaSysMenuNameKey)
	return err
}

func (m *defaultSysMenuModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultSysMenuModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, id)
		kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, data.Name)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaSysMenuIdKey, kubeNovaSysMenuNameKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultSysMenuModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, id)
		kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, data.Name)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaSysMenuIdKey, kubeNovaSysMenuNameKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultSysMenuModel) FindOne(ctx context.Context, id uint64) (*SysMenu, error) {
	kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, id)
	var resp SysMenu
	err := m.QueryRowCtx(ctx, &resp, kubeNovaSysMenuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysMenuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysMenu, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*SysMenu
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*SysMenu{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", sysMenuRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultSysMenuModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysMenu, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", sysMenuRows, m.table, where, orderStr)
	var resp []*SysMenu

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*SysMenu{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*SysMenu{}, nil
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) FindOneByName(ctx context.Context, name string) (*SysMenu, error) {
	kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, name)
	var resp SysMenu
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaSysMenuNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", sysMenuRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) Insert(ctx context.Context, data *SysMenu) (sql.Result, error) {
	kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, data.Id)
	kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysMenuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.PlatformId, data.MenuType, data.Name, data.Path, data.Component, data.Redirect, data.Label, data.Title, data.Icon, data.Sort, data.Link, data.IsEnable, data.IsMenu, data.KeepAlive, data.IsHide, data.IsIframe, data.IsHideTab, data.ShowBadge, data.ShowTextBadge, data.IsFirstLevel, data.FixedTab, data.IsFullPage, data.ActivePath, data.Roles, data.AuthName, data.AuthLabel, data.AuthIcon, data.AuthSort, data.Status, data.IsDeleted, data.CreateBy, data.UpdateBy)
	}, kubeNovaSysMenuIdKey, kubeNovaSysMenuNameKey)
	return ret, err
}

func (m *defaultSysMenuModel) Update(ctx context.Context, newData *SysMenu) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaSysMenuIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, data.Id)
	kubeNovaSysMenuNameKey := fmt.Sprintf("%s%v", cacheKubeNovaSysMenuNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysMenuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ParentId, newData.PlatformId, newData.MenuType, newData.Name, newData.Path, newData.Component, newData.Redirect, newData.Label, newData.Title, newData.Icon, newData.Sort, newData.Link, newData.IsEnable, newData.IsMenu, newData.KeepAlive, newData.IsHide, newData.IsIframe, newData.IsHideTab, newData.ShowBadge, newData.ShowTextBadge, newData.IsFirstLevel, newData.FixedTab, newData.IsFullPage, newData.ActivePath, newData.Roles, newData.AuthName, newData.AuthLabel, newData.AuthIcon, newData.AuthSort, newData.Status, newData.IsDeleted, newData.CreateBy, newData.UpdateBy, newData.Id)
	}, kubeNovaSysMenuIdKey, kubeNovaSysMenuNameKey)
	return err
}

func (m *defaultSysMenuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaSysMenuIdPrefix, primary)
}

func (m *defaultSysMenuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysMenuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysMenuModel) tableName() string {
	return m.table
}
