// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysPlatformFieldNames          = builder.RawFieldNames(&SysPlatform{})
	sysPlatformRows                = strings.Join(sysPlatformFieldNames, ",")
	sysPlatformRowsExpectAutoSet   = strings.Join(stringx.Remove(sysPlatformFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysPlatformRowsWithPlaceHolder = strings.Join(stringx.Remove(sysPlatformFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaSysPlatformIdPrefix           = "cache:kubeNova:sysPlatform:id:"
	cacheKubeNovaSysPlatformPlatformCodePrefix = "cache:kubeNova:sysPlatform:platformCode:"
)

type (
	sysPlatformModel interface {
		Insert(ctx context.Context, data *SysPlatform) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SysPlatform, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysPlatform, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysPlatform, error)
		FindOneByPlatformCode(ctx context.Context, platformCode string) (*SysPlatform, error)
		Update(ctx context.Context, data *SysPlatform) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultSysPlatformModel struct {
		sqlc.CachedConn
		table string
	}

	SysPlatform struct {
		Id           uint64         `db:"id"`            // 自增主键
		PlatformCode string         `db:"platform_code"` // 平台编码（唯一标识，如：container、microservice、devops）
		PlatformName string         `db:"platform_name"` // 平台名称（如：容器平台、微服务平台、DevOps平台）
		PlatformDesc string         `db:"platform_desc"` // 平台描述
		PlatformIcon string         `db:"platform_icon"` // 平台图标
		Sort         int64          `db:"sort"`          // 排序（数字越小越靠前）
		IsEnable     int64          `db:"is_enable"`     // 是否启用（0:禁用 1:启用）
		IsDefault    int64          `db:"is_default"`    // 是否为默认平台（0:否 1:是，全局只能有一个默认平台）
		IsDeleted    int64          `db:"is_deleted"`    // 是否删除（0:正常 1:已删除）
		CreateTime   time.Time      `db:"create_time"`   // 创建时间
		UpdateTime   time.Time      `db:"update_time"`   // 更新时间
		CreateBy     sql.NullString `db:"create_by"`     // 创建人
		UpdateBy     sql.NullString `db:"update_by"`     // 更新人
	}
)

func newSysPlatformModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysPlatformModel {
	return &defaultSysPlatformModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_platform`",
	}
}

func (m *defaultSysPlatformModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, id)
	kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, data.PlatformCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaSysPlatformIdKey, kubeNovaSysPlatformPlatformCodeKey)
	return err
}

func (m *defaultSysPlatformModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, id)
	kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, data.PlatformCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaSysPlatformIdKey, kubeNovaSysPlatformPlatformCodeKey)
	return err
}

func (m *defaultSysPlatformModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultSysPlatformModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, id)
		kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, data.PlatformCode)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaSysPlatformIdKey, kubeNovaSysPlatformPlatformCodeKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultSysPlatformModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, id)
		kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, data.PlatformCode)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaSysPlatformIdKey, kubeNovaSysPlatformPlatformCodeKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultSysPlatformModel) FindOne(ctx context.Context, id uint64) (*SysPlatform, error) {
	kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, id)
	var resp SysPlatform
	err := m.QueryRowCtx(ctx, &resp, kubeNovaSysPlatformIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysPlatformRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPlatformModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysPlatform, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*SysPlatform
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*SysPlatform{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", sysPlatformRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultSysPlatformModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysPlatform, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", sysPlatformRows, m.table, where, orderStr)
	var resp []*SysPlatform

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*SysPlatform{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*SysPlatform{}, nil
	default:
		return nil, err
	}
}

func (m *defaultSysPlatformModel) FindOneByPlatformCode(ctx context.Context, platformCode string) (*SysPlatform, error) {
	kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, platformCode)
	var resp SysPlatform
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaSysPlatformPlatformCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `platform_code` = ? limit 1", sysPlatformRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, platformCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPlatformModel) Insert(ctx context.Context, data *SysPlatform) (sql.Result, error) {
	kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, data.Id)
	kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, data.PlatformCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysPlatformRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PlatformCode, data.PlatformName, data.PlatformDesc, data.PlatformIcon, data.Sort, data.IsEnable, data.IsDefault, data.IsDeleted, data.CreateBy, data.UpdateBy)
	}, kubeNovaSysPlatformIdKey, kubeNovaSysPlatformPlatformCodeKey)
	return ret, err
}

func (m *defaultSysPlatformModel) Update(ctx context.Context, newData *SysPlatform) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaSysPlatformIdKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, data.Id)
	kubeNovaSysPlatformPlatformCodeKey := fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformPlatformCodePrefix, data.PlatformCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysPlatformRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PlatformCode, newData.PlatformName, newData.PlatformDesc, newData.PlatformIcon, newData.Sort, newData.IsEnable, newData.IsDefault, newData.IsDeleted, newData.CreateBy, newData.UpdateBy, newData.Id)
	}, kubeNovaSysPlatformIdKey, kubeNovaSysPlatformPlatformCodeKey)
	return err
}

func (m *defaultSysPlatformModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaSysPlatformIdPrefix, primary)
}

func (m *defaultSysPlatformModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysPlatformRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysPlatformModel) tableName() string {
	return m.table
}
