// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	alertInstanceLifecycleFieldNames          = builder.RawFieldNames(&AlertInstanceLifecycle{})
	alertInstanceLifecycleRows                = strings.Join(alertInstanceLifecycleFieldNames, ",")
	alertInstanceLifecycleRowsExpectAutoSet   = strings.Join(stringx.Remove(alertInstanceLifecycleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	alertInstanceLifecycleRowsWithPlaceHolder = strings.Join(stringx.Remove(alertInstanceLifecycleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaAlertInstanceLifecycleIdPrefix         = "cache:kubeNova:alertInstanceLifecycle:id:"
	cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix = "cache:kubeNova:alertInstanceLifecycle:instanceId:"
)

type (
	alertInstanceLifecycleModel interface {
		Insert(ctx context.Context, data *AlertInstanceLifecycle) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AlertInstanceLifecycle, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*AlertInstanceLifecycle, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*AlertInstanceLifecycle, error)
		FindOneByInstanceId(ctx context.Context, instanceId uint64) (*AlertInstanceLifecycle, error)
		Update(ctx context.Context, data *AlertInstanceLifecycle) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultAlertInstanceLifecycleModel struct {
		sqlc.CachedConn
		table string
	}

	AlertInstanceLifecycle struct {
		Id             uint64       `db:"id"`               // 主键ID
		InstanceId     uint64       `db:"instance_id"`      // 告警实例ID
		LifecycleState string       `db:"lifecycle_state"`  // 生命周期状态: new/assigned/acknowledged/resolving/resolved/closed/reopened
		AssigneeUserId uint64       `db:"assignee_user_id"` // 处理人用户ID
		AssignedAt     sql.NullTime `db:"assigned_at"`      // 分配时间
		AssignedBy     string       `db:"assigned_by"`      // 分配操作人
		AckAt          sql.NullTime `db:"ack_at"`           // 确认时间
		ResolvedBy     string       `db:"resolved_by"`      // 解决人
		ResolveAt      sql.NullTime `db:"resolve_at"`       // 解决时间
		ResolveNote    string       `db:"resolve_note"`     // 解决说明
		CloseAt        sql.NullTime `db:"close_at"`         // 关闭时间
		ReopenedAt     sql.NullTime `db:"reopened_at"`      // 重开时间
		CreatedBy      string       `db:"created_by"`       // 记录创建人
		UpdatedBy      string       `db:"updated_by"`       // 记录最后更新人
		CreatedAt      time.Time    `db:"created_at"`       // 记录创建时间
		UpdatedAt      time.Time    `db:"updated_at"`       // 记录更新时间
		IsDeleted      int64        `db:"is_deleted"`       // 是否已删除，软删除标记
	}
)

func newAlertInstanceLifecycleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAlertInstanceLifecycleModel {
	return &defaultAlertInstanceLifecycleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`alert_instance_lifecycle`",
	}
}

func (m *defaultAlertInstanceLifecycleModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, id)
	kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, data.InstanceId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaAlertInstanceLifecycleIdKey, kubeNovaAlertInstanceLifecycleInstanceIdKey)
	return err
}

func (m *defaultAlertInstanceLifecycleModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, id)
	kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, data.InstanceId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaAlertInstanceLifecycleIdKey, kubeNovaAlertInstanceLifecycleInstanceIdKey)
	return err
}

func (m *defaultAlertInstanceLifecycleModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultAlertInstanceLifecycleModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, id)
		kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, data.InstanceId)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaAlertInstanceLifecycleIdKey, kubeNovaAlertInstanceLifecycleInstanceIdKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultAlertInstanceLifecycleModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, id)
		kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, data.InstanceId)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaAlertInstanceLifecycleIdKey, kubeNovaAlertInstanceLifecycleInstanceIdKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultAlertInstanceLifecycleModel) FindOne(ctx context.Context, id uint64) (*AlertInstanceLifecycle, error) {
	kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, id)
	var resp AlertInstanceLifecycle
	err := m.QueryRowCtx(ctx, &resp, kubeNovaAlertInstanceLifecycleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", alertInstanceLifecycleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAlertInstanceLifecycleModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*AlertInstanceLifecycle, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*AlertInstanceLifecycle
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*AlertInstanceLifecycle{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", alertInstanceLifecycleRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultAlertInstanceLifecycleModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*AlertInstanceLifecycle, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", alertInstanceLifecycleRows, m.table, where, orderStr)
	var resp []*AlertInstanceLifecycle

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*AlertInstanceLifecycle{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*AlertInstanceLifecycle{}, nil
	default:
		return nil, err
	}
}

func (m *defaultAlertInstanceLifecycleModel) FindOneByInstanceId(ctx context.Context, instanceId uint64) (*AlertInstanceLifecycle, error) {
	kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, instanceId)
	var resp AlertInstanceLifecycle
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaAlertInstanceLifecycleInstanceIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `instance_id` = ? limit 1", alertInstanceLifecycleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, instanceId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAlertInstanceLifecycleModel) Insert(ctx context.Context, data *AlertInstanceLifecycle) (sql.Result, error) {
	kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, data.Id)
	kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, data.InstanceId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, alertInstanceLifecycleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InstanceId, data.LifecycleState, data.AssigneeUserId, data.AssignedAt, data.AssignedBy, data.AckAt, data.ResolvedBy, data.ResolveAt, data.ResolveNote, data.CloseAt, data.ReopenedAt, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaAlertInstanceLifecycleIdKey, kubeNovaAlertInstanceLifecycleInstanceIdKey)
	return ret, err
}

func (m *defaultAlertInstanceLifecycleModel) Update(ctx context.Context, newData *AlertInstanceLifecycle) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaAlertInstanceLifecycleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, data.Id)
	kubeNovaAlertInstanceLifecycleInstanceIdKey := fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleInstanceIdPrefix, data.InstanceId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, alertInstanceLifecycleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.InstanceId, newData.LifecycleState, newData.AssigneeUserId, newData.AssignedAt, newData.AssignedBy, newData.AckAt, newData.ResolvedBy, newData.ResolveAt, newData.ResolveNote, newData.CloseAt, newData.ReopenedAt, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeNovaAlertInstanceLifecycleIdKey, kubeNovaAlertInstanceLifecycleInstanceIdKey)
	return err
}

func (m *defaultAlertInstanceLifecycleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaAlertInstanceLifecycleIdPrefix, primary)
}

func (m *defaultAlertInstanceLifecycleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", alertInstanceLifecycleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAlertInstanceLifecycleModel) tableName() string {
	return m.table
}
