// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	alertRulesFieldNames          = builder.RawFieldNames(&AlertRules{})
	alertRulesRows                = strings.Join(alertRulesFieldNames, ",")
	alertRulesRowsExpectAutoSet   = strings.Join(stringx.Remove(alertRulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	alertRulesRowsWithPlaceHolder = strings.Join(stringx.Remove(alertRulesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsAlertRulesIdPrefix               = "cache:ikubeops:alertRules:id:"
	cacheIkubeopsAlertRulesGroupIdAlertNamePrefix = "cache:ikubeops:alertRules:groupId:alertName:"
)

type (
	alertRulesModel interface {
		Insert(ctx context.Context, data *AlertRules) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AlertRules, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*AlertRules, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*AlertRules, error)
		FindOneByGroupIdAlertName(ctx context.Context, groupId uint64, alertName string) (*AlertRules, error)
		Update(ctx context.Context, data *AlertRules) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultAlertRulesModel struct {
		sqlc.CachedConn
		table string
	}

	AlertRules struct {
		Id          uint64         `db:"id"`           // 主键ID
		GroupId     uint64         `db:"group_id"`     // 所属分组ID
		AlertName   string         `db:"alert_name"`   // 告警名称(alert字段,英文)
		RuleNameCn  string         `db:"rule_name_cn"` // 规则中文名
		Expr        string         `db:"expr"`         // PromQL表达式
		ForDuration string         `db:"for_duration"` // 持续时间(0m, 1m, 5m, 10m)
		Severity    string         `db:"severity"`     // 告警级别(critical, warning, info)
		Summary     string         `db:"summary"`      // 告警摘要(annotations.summary)
		Description sql.NullString `db:"description"`  // 告警详细描述(annotations.description)
		Labels      sql.NullString `db:"labels"`       // 额外标签(JSON格式)
		Annotations sql.NullString `db:"annotations"`  // 额外注解(JSON格式)
		IsEnabled   int64          `db:"is_enabled"`   // 是否启用
		SortOrder   int64          `db:"sort_order"`   // 排序序号
		CreatedBy   string         `db:"created_by"`   // 创建人
		UpdatedBy   string         `db:"updated_by"`   // 更新人
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		IsDeleted   int64          `db:"is_deleted"`   // 是否删除
	}
)

func newAlertRulesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAlertRulesModel {
	return &defaultAlertRulesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`alert_rules`",
	}
}

func (m *defaultAlertRulesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, data.GroupId, data.AlertName)
	ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsAlertRulesGroupIdAlertNameKey, ikubeopsAlertRulesIdKey)
	return err
}

func (m *defaultAlertRulesModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, data.GroupId, data.AlertName)
	ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsAlertRulesGroupIdAlertNameKey, ikubeopsAlertRulesIdKey)
	return err
}

func (m *defaultAlertRulesModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultAlertRulesModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, data.GroupId, data.AlertName)
		ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, id)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsAlertRulesGroupIdAlertNameKey, ikubeopsAlertRulesIdKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultAlertRulesModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, data.GroupId, data.AlertName)
		ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, id)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsAlertRulesGroupIdAlertNameKey, ikubeopsAlertRulesIdKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultAlertRulesModel) FindOne(ctx context.Context, id uint64) (*AlertRules, error) {
	ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, id)
	var resp AlertRules
	err := m.QueryRowCtx(ctx, &resp, ikubeopsAlertRulesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", alertRulesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAlertRulesModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*AlertRules, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*AlertRules
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*AlertRules{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", alertRulesRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultAlertRulesModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*AlertRules, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", alertRulesRows, m.table, where, orderStr)
	var resp []*AlertRules

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*AlertRules{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*AlertRules{}, nil
	default:
		return nil, err
	}
}

func (m *defaultAlertRulesModel) FindOneByGroupIdAlertName(ctx context.Context, groupId uint64, alertName string) (*AlertRules, error) {
	ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, groupId, alertName)
	var resp AlertRules
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsAlertRulesGroupIdAlertNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? and `alert_name` = ? limit 1", alertRulesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId, alertName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAlertRulesModel) Insert(ctx context.Context, data *AlertRules) (sql.Result, error) {
	ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, data.GroupId, data.AlertName)
	ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, alertRulesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.AlertName, data.RuleNameCn, data.Expr, data.ForDuration, data.Severity, data.Summary, data.Description, data.Labels, data.Annotations, data.IsEnabled, data.SortOrder, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, ikubeopsAlertRulesGroupIdAlertNameKey, ikubeopsAlertRulesIdKey)
	return ret, err
}

func (m *defaultAlertRulesModel) Update(ctx context.Context, newData *AlertRules) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsAlertRulesGroupIdAlertNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsAlertRulesGroupIdAlertNamePrefix, data.GroupId, data.AlertName)
	ikubeopsAlertRulesIdKey := fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, alertRulesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.AlertName, newData.RuleNameCn, newData.Expr, newData.ForDuration, newData.Severity, newData.Summary, newData.Description, newData.Labels, newData.Annotations, newData.IsEnabled, newData.SortOrder, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, ikubeopsAlertRulesGroupIdAlertNameKey, ikubeopsAlertRulesIdKey)
	return err
}

func (m *defaultAlertRulesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsAlertRulesIdPrefix, primary)
}

func (m *defaultAlertRulesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", alertRulesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAlertRulesModel) tableName() string {
	return m.table
}
