// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecLogAlertRuleFieldNames          = builder.RawFieldNames(&OnecLogAlertRule{})
	onecLogAlertRuleRows                = strings.Join(onecLogAlertRuleFieldNames, ",")
	onecLogAlertRuleRowsExpectAutoSet   = strings.Join(stringx.Remove(onecLogAlertRuleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecLogAlertRuleRowsWithPlaceHolder = strings.Join(stringx.Remove(onecLogAlertRuleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaOnecLogAlertRuleIdPrefix = "cache:kubeNova:onecLogAlertRule:id:"
)

type (
	onecLogAlertRuleModel interface {
		Insert(ctx context.Context, data *OnecLogAlertRule) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OnecLogAlertRule, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecLogAlertRule, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecLogAlertRule, error)
		Update(ctx context.Context, data *OnecLogAlertRule) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecLogAlertRuleModel struct {
		sqlc.CachedConn
		table string
	}

	OnecLogAlertRule struct {
		Id             uint64         `db:"id"`               // 主键ID
		ClusterUuid    string         `db:"cluster_uuid"`     // 集群UUID
		BackendType    string         `db:"backend_type"`     // 日志后端类型
		ProjectUuid    string         `db:"project_uuid"`     // 项目UUID
		WorkspaceId    uint64         `db:"workspace_id"`     // 工作空间ID
		Namespace      string         `db:"namespace"`        // 命名空间
		Application    string         `db:"application"`      // 应用英文名
		ResourceName   string         `db:"resource_name"`    // 资源名称
		Name           string         `db:"name"`             // 规则名称
		Description    string         `db:"description"`      // 规则描述
		QueryText      string         `db:"query_text"`       // 查询表达式或关键字
		ConditionType  string         `db:"condition_type"`   // 条件类型
		Threshold      string         `db:"threshold"`        // 阈值
		Window         string         `db:"window"`           // 时间窗口
		Severity       string         `db:"severity"`         // 严重级别
		NotifyChannels sql.NullString `db:"notify_channels"`  // 通知渠道JSON
		Enabled        int64          `db:"enabled"`          // 是否启用
		BackendRuleId  string         `db:"backend_rule_id"`  // 后端规则ID
		BackendPayload sql.NullString `db:"backend_payload"`  // 后端规则原始载荷
		LastSyncStatus string         `db:"last_sync_status"` // 最近同步状态
		LastSyncError  sql.NullString `db:"last_sync_error"`  // 最近同步错误
		LogType        string         `db:"log_type"`         // 日志类型: container/system
		SearchMode     string         `db:"search_mode"`      // 查询模式: form/code
		Expr           sql.NullString `db:"expr"`             // 原生查询表达式
		EvalInterval   string         `db:"eval_interval"`    // 评估周期
		ForDuration    string         `db:"for_duration"`     // 持续触发时长
		SilenceWindow  string         `db:"silence_window"`   // 告警静默窗口
		RuleVersion    uint64         `db:"rule_version"`     // 规则版本号
		LastEvalAt     sql.NullTime   `db:"last_eval_at"`     // 最近评估时间
		NextEvalAt     sql.NullTime   `db:"next_eval_at"`     // 下次评估时间
		CreatedBy      string         `db:"created_by"`       // 记录创建人
		UpdatedBy      string         `db:"updated_by"`       // 记录最后更新人
		CreatedAt      time.Time      `db:"created_at"`       // 记录创建时间
		UpdatedAt      time.Time      `db:"updated_at"`       // 记录更新时间
		IsDeleted      int64          `db:"is_deleted"`       // 是否已删除，软删除标记
	}
)

func newOnecLogAlertRuleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecLogAlertRuleModel {
	return &defaultOnecLogAlertRuleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_log_alert_rule`",
	}
}

func (m *defaultOnecLogAlertRuleModel) Delete(ctx context.Context, id uint64) error {
	kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecLogAlertRuleIdKey)
	return err
}

func (m *defaultOnecLogAlertRuleModel) DeleteSoft(ctx context.Context, id uint64) error {
	kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecLogAlertRuleIdKey)
	return err
}

func (m *defaultOnecLogAlertRuleModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecLogAlertRuleModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）

		// 处理缓存逻辑
		kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, id)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecLogAlertRuleIdKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultOnecLogAlertRuleModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）

		// 处理缓存逻辑
		kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, id)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecLogAlertRuleIdKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultOnecLogAlertRuleModel) FindOne(ctx context.Context, id uint64) (*OnecLogAlertRule, error) {
	kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, id)
	var resp OnecLogAlertRule
	err := m.QueryRowCtx(ctx, &resp, kubeNovaOnecLogAlertRuleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecLogAlertRuleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecLogAlertRuleModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecLogAlertRule, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecLogAlertRule
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*OnecLogAlertRule{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecLogAlertRuleRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecLogAlertRuleModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecLogAlertRule, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecLogAlertRuleRows, m.table, where, orderStr)
	var resp []*OnecLogAlertRule

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*OnecLogAlertRule{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*OnecLogAlertRule{}, nil
	default:
		return nil, err
	}
}

func (m *defaultOnecLogAlertRuleModel) Insert(ctx context.Context, data *OnecLogAlertRule) (sql.Result, error) {
	kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecLogAlertRuleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClusterUuid, data.BackendType, data.ProjectUuid, data.WorkspaceId, data.Namespace, data.Application, data.ResourceName, data.Name, data.Description, data.QueryText, data.ConditionType, data.Threshold, data.Window, data.Severity, data.NotifyChannels, data.Enabled, data.BackendRuleId, data.BackendPayload, data.LastSyncStatus, data.LastSyncError, data.LogType, data.SearchMode, data.Expr, data.EvalInterval, data.ForDuration, data.SilenceWindow, data.RuleVersion, data.LastEvalAt, data.NextEvalAt, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaOnecLogAlertRuleIdKey)
	return ret, err
}

func (m *defaultOnecLogAlertRuleModel) Update(ctx context.Context, data *OnecLogAlertRule) error {
	kubeNovaOnecLogAlertRuleIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecLogAlertRuleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ClusterUuid, data.BackendType, data.ProjectUuid, data.WorkspaceId, data.Namespace, data.Application, data.ResourceName, data.Name, data.Description, data.QueryText, data.ConditionType, data.Threshold, data.Window, data.Severity, data.NotifyChannels, data.Enabled, data.BackendRuleId, data.BackendPayload, data.LastSyncStatus, data.LastSyncError, data.LogType, data.SearchMode, data.Expr, data.EvalInterval, data.ForDuration, data.SilenceWindow, data.RuleVersion, data.LastEvalAt, data.NextEvalAt, data.CreatedBy, data.UpdatedBy, data.IsDeleted, data.Id)
	}, kubeNovaOnecLogAlertRuleIdKey)
	return err
}

func (m *defaultOnecLogAlertRuleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertRuleIdPrefix, primary)
}

func (m *defaultOnecLogAlertRuleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecLogAlertRuleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecLogAlertRuleModel) tableName() string {
	return m.table
}
