// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecInspectionRecordFieldNames          = builder.RawFieldNames(&OnecInspectionRecord{})
	onecInspectionRecordRows                = strings.Join(onecInspectionRecordFieldNames, ",")
	onecInspectionRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(onecInspectionRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecInspectionRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(onecInspectionRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaOnecInspectionRecordIdPrefix       = "cache:kubeNova:onecInspectionRecord:id:"
	cacheKubeNovaOnecInspectionRecordRecordNoPrefix = "cache:kubeNova:onecInspectionRecord:recordNo:"
)

type (
	onecInspectionRecordModel interface {
		Insert(ctx context.Context, data *OnecInspectionRecord) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OnecInspectionRecord, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionRecord, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionRecord, error)
		FindOneByRecordNo(ctx context.Context, recordNo string) (*OnecInspectionRecord, error)
		Update(ctx context.Context, data *OnecInspectionRecord) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecInspectionRecordModel struct {
		sqlc.CachedConn
		table string
	}

	OnecInspectionRecord struct {
		Id            uint64         `db:"id"`             // 主键ID
		RecordNo      string         `db:"record_no"`      // 巡检记录编号
		TaskId        uint64         `db:"task_id"`        // 巡检任务ID
		TemplateId    uint64         `db:"template_id"`    // 巡检模板ID
		TriggerType   string         `db:"trigger_type"`   // 触发类型：manual手动/schedule定时
		ScopeType     string         `db:"scope_type"`     // 巡检范围：global全局/cluster单集群
		ClusterUuid   string         `db:"cluster_uuid"`   // 集群UUID
		ClusterName   string         `db:"cluster_name"`   // 集群名称快照
		Status        string         `db:"status"`         // 执行状态：running/success/failed/partial
		Score         float64        `db:"score"`          // 巡检得分
		HealthLevel   string         `db:"health_level"`   // 健康等级：healthy/warning/critical/unknown
		TotalCount    int64          `db:"total_count"`    // 巡检项总数
		SuccessCount  int64          `db:"success_count"`  // 正常项数量
		WarningCount  int64          `db:"warning_count"`  // 警告项数量
		CriticalCount int64          `db:"critical_count"` // 严重项数量
		FailedCount   int64          `db:"failed_count"`   // 执行失败项数量
		SummaryJson   sql.NullString `db:"summary_json"`   // 巡检摘要JSON
		ReportJson    sql.NullString `db:"report_json"`    // 巡检报告JSON
		StartedAt     sql.NullTime   `db:"started_at"`     // 开始时间
		FinishedAt    sql.NullTime   `db:"finished_at"`    // 结束时间
		DurationMs    int64          `db:"duration_ms"`    // 执行耗时毫秒
		ErrorMessage  string         `db:"error_message"`  // 错误信息
		CreatedBy     string         `db:"created_by"`     // 记录创建人
		UpdatedBy     string         `db:"updated_by"`     // 记录最后更新人
		CreatedAt     time.Time      `db:"created_at"`     // 记录创建时间
		UpdatedAt     time.Time      `db:"updated_at"`     // 记录更新时间
		IsDeleted     int64          `db:"is_deleted"`     // 是否已删除，软删除标记
	}
)

func newOnecInspectionRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecInspectionRecordModel {
	return &defaultOnecInspectionRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_inspection_record`",
	}
}

func (m *defaultOnecInspectionRecordModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, id)
	kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, data.RecordNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionRecordIdKey, kubeNovaOnecInspectionRecordRecordNoKey)
	return err
}

func (m *defaultOnecInspectionRecordModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, id)
	kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, data.RecordNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionRecordIdKey, kubeNovaOnecInspectionRecordRecordNoKey)
	return err
}

func (m *defaultOnecInspectionRecordModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecInspectionRecordModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, id)
		kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, data.RecordNo)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionRecordIdKey, kubeNovaOnecInspectionRecordRecordNoKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultOnecInspectionRecordModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, id)
		kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, data.RecordNo)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionRecordIdKey, kubeNovaOnecInspectionRecordRecordNoKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultOnecInspectionRecordModel) FindOne(ctx context.Context, id uint64) (*OnecInspectionRecord, error) {
	kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, id)
	var resp OnecInspectionRecord
	err := m.QueryRowCtx(ctx, &resp, kubeNovaOnecInspectionRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionRecordModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionRecord, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecInspectionRecord
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*OnecInspectionRecord{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecInspectionRecordRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecInspectionRecordModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionRecord, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecInspectionRecordRows, m.table, where, orderStr)
	var resp []*OnecInspectionRecord

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*OnecInspectionRecord{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*OnecInspectionRecord{}, nil
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionRecordModel) FindOneByRecordNo(ctx context.Context, recordNo string) (*OnecInspectionRecord, error) {
	kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, recordNo)
	var resp OnecInspectionRecord
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaOnecInspectionRecordRecordNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `record_no` = ? limit 1", onecInspectionRecordRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, recordNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionRecordModel) Insert(ctx context.Context, data *OnecInspectionRecord) (sql.Result, error) {
	kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, data.Id)
	kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, data.RecordNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecInspectionRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RecordNo, data.TaskId, data.TemplateId, data.TriggerType, data.ScopeType, data.ClusterUuid, data.ClusterName, data.Status, data.Score, data.HealthLevel, data.TotalCount, data.SuccessCount, data.WarningCount, data.CriticalCount, data.FailedCount, data.SummaryJson, data.ReportJson, data.StartedAt, data.FinishedAt, data.DurationMs, data.ErrorMessage, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaOnecInspectionRecordIdKey, kubeNovaOnecInspectionRecordRecordNoKey)
	return ret, err
}

func (m *defaultOnecInspectionRecordModel) Update(ctx context.Context, newData *OnecInspectionRecord) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaOnecInspectionRecordIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, data.Id)
	kubeNovaOnecInspectionRecordRecordNoKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordRecordNoPrefix, data.RecordNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecInspectionRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RecordNo, newData.TaskId, newData.TemplateId, newData.TriggerType, newData.ScopeType, newData.ClusterUuid, newData.ClusterName, newData.Status, newData.Score, newData.HealthLevel, newData.TotalCount, newData.SuccessCount, newData.WarningCount, newData.CriticalCount, newData.FailedCount, newData.SummaryJson, newData.ReportJson, newData.StartedAt, newData.FinishedAt, newData.DurationMs, newData.ErrorMessage, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeNovaOnecInspectionRecordIdKey, kubeNovaOnecInspectionRecordRecordNoKey)
	return err
}

func (m *defaultOnecInspectionRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionRecordIdPrefix, primary)
}

func (m *defaultOnecInspectionRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecInspectionRecordModel) tableName() string {
	return m.table
}
