// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecInspectionItemFieldNames          = builder.RawFieldNames(&OnecInspectionItem{})
	onecInspectionItemRows                = strings.Join(onecInspectionItemFieldNames, ",")
	onecInspectionItemRowsExpectAutoSet   = strings.Join(stringx.Remove(onecInspectionItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecInspectionItemRowsWithPlaceHolder = strings.Join(stringx.Remove(onecInspectionItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaOnecInspectionItemIdPrefix                 = "cache:kubeNova:onecInspectionItem:id:"
	cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix = "cache:kubeNova:onecInspectionItem:templateId:itemCode:"
)

type (
	onecInspectionItemModel interface {
		Insert(ctx context.Context, data *OnecInspectionItem) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OnecInspectionItem, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionItem, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionItem, error)
		FindOneByTemplateIdItemCode(ctx context.Context, templateId uint64, itemCode string) (*OnecInspectionItem, error)
		Update(ctx context.Context, data *OnecInspectionItem) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecInspectionItemModel struct {
		sqlc.CachedConn
		table string
	}

	OnecInspectionItem struct {
		Id         uint64         `db:"id"`          // 主键ID
		TemplateId uint64         `db:"template_id"` // 巡检模板ID
		GroupId    uint64         `db:"group_id"`    // 巡检分组ID
		ItemCode   string         `db:"item_code"`   // 巡检项编码
		ItemName   string         `db:"item_name"`   // 巡检项名称
		Category   string         `db:"category"`    // 巡检分类
		CheckType  string         `db:"check_type"`  // 检查类型：builtin内置/promql指标/sql数据
		TargetType string         `db:"target_type"` // 目标类型：cluster/node/pod/workload/prometheus
		Severity   string         `db:"severity"`    // 严重级别：critical/warning/info
		Weight     int64          `db:"weight"`      // 评分权重
		Enabled    int64          `db:"enabled"`     // 是否启用
		TimeoutSec int64          `db:"timeout_sec"` // 执行超时时间秒
		OrderNum   int64          `db:"order_num"`   // 排序号
		Promql     sql.NullString `db:"promql"`      // PromQL表达式
		Operator   string         `db:"operator"`    // 比较运算符
		Threshold  string         `db:"threshold"`   // 阈值
		Unit       string         `db:"unit"`        // 指标单位
		ConfigJson sql.NullString `db:"config_json"` // 巡检项扩展配置JSON
		Advice     string         `db:"advice"`      // 处理建议
		CreatedBy  string         `db:"created_by"`  // 记录创建人
		UpdatedBy  string         `db:"updated_by"`  // 记录最后更新人
		CreatedAt  time.Time      `db:"created_at"`  // 记录创建时间
		UpdatedAt  time.Time      `db:"updated_at"`  // 记录更新时间
		IsDeleted  int64          `db:"is_deleted"`  // 是否已删除，软删除标记
	}
)

func newOnecInspectionItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecInspectionItemModel {
	return &defaultOnecInspectionItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_inspection_item`",
	}
}

func (m *defaultOnecInspectionItemModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, id)
	kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, data.TemplateId, data.ItemCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionItemIdKey, kubeNovaOnecInspectionItemTemplateIdItemCodeKey)
	return err
}

func (m *defaultOnecInspectionItemModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, id)
	kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, data.TemplateId, data.ItemCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionItemIdKey, kubeNovaOnecInspectionItemTemplateIdItemCodeKey)
	return err
}

func (m *defaultOnecInspectionItemModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecInspectionItemModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, id)
		kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, data.TemplateId, data.ItemCode)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionItemIdKey, kubeNovaOnecInspectionItemTemplateIdItemCodeKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultOnecInspectionItemModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, id)
		kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, data.TemplateId, data.ItemCode)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionItemIdKey, kubeNovaOnecInspectionItemTemplateIdItemCodeKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultOnecInspectionItemModel) FindOne(ctx context.Context, id uint64) (*OnecInspectionItem, error) {
	kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, id)
	var resp OnecInspectionItem
	err := m.QueryRowCtx(ctx, &resp, kubeNovaOnecInspectionItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionItemModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionItem, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecInspectionItem
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*OnecInspectionItem{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecInspectionItemRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecInspectionItemModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionItem, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecInspectionItemRows, m.table, where, orderStr)
	var resp []*OnecInspectionItem

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*OnecInspectionItem{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*OnecInspectionItem{}, nil
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionItemModel) FindOneByTemplateIdItemCode(ctx context.Context, templateId uint64, itemCode string) (*OnecInspectionItem, error) {
	kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, templateId, itemCode)
	var resp OnecInspectionItem
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaOnecInspectionItemTemplateIdItemCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `template_id` = ? and `item_code` = ? limit 1", onecInspectionItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, templateId, itemCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionItemModel) Insert(ctx context.Context, data *OnecInspectionItem) (sql.Result, error) {
	kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, data.Id)
	kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, data.TemplateId, data.ItemCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecInspectionItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TemplateId, data.GroupId, data.ItemCode, data.ItemName, data.Category, data.CheckType, data.TargetType, data.Severity, data.Weight, data.Enabled, data.TimeoutSec, data.OrderNum, data.Promql, data.Operator, data.Threshold, data.Unit, data.ConfigJson, data.Advice, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaOnecInspectionItemIdKey, kubeNovaOnecInspectionItemTemplateIdItemCodeKey)
	return ret, err
}

func (m *defaultOnecInspectionItemModel) Update(ctx context.Context, newData *OnecInspectionItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaOnecInspectionItemIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, data.Id)
	kubeNovaOnecInspectionItemTemplateIdItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionItemTemplateIdItemCodePrefix, data.TemplateId, data.ItemCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecInspectionItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TemplateId, newData.GroupId, newData.ItemCode, newData.ItemName, newData.Category, newData.CheckType, newData.TargetType, newData.Severity, newData.Weight, newData.Enabled, newData.TimeoutSec, newData.OrderNum, newData.Promql, newData.Operator, newData.Threshold, newData.Unit, newData.ConfigJson, newData.Advice, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeNovaOnecInspectionItemIdKey, kubeNovaOnecInspectionItemTemplateIdItemCodeKey)
	return err
}

func (m *defaultOnecInspectionItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionItemIdPrefix, primary)
}

func (m *defaultOnecInspectionItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecInspectionItemModel) tableName() string {
	return m.table
}
