// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecInspectionGroupFieldNames          = builder.RawFieldNames(&OnecInspectionGroup{})
	onecInspectionGroupRows                = strings.Join(onecInspectionGroupFieldNames, ",")
	onecInspectionGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(onecInspectionGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecInspectionGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(onecInspectionGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaOnecInspectionGroupIdPrefix                  = "cache:kubeNova:onecInspectionGroup:id:"
	cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix = "cache:kubeNova:onecInspectionGroup:templateId:groupCode:"
)

type (
	onecInspectionGroupModel interface {
		Insert(ctx context.Context, data *OnecInspectionGroup) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OnecInspectionGroup, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionGroup, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionGroup, error)
		FindOneByTemplateIdGroupCode(ctx context.Context, templateId uint64, groupCode string) (*OnecInspectionGroup, error)
		Update(ctx context.Context, data *OnecInspectionGroup) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecInspectionGroupModel struct {
		sqlc.CachedConn
		table string
	}

	OnecInspectionGroup struct {
		Id          uint64         `db:"id"`          // 主键ID
		TemplateId  uint64         `db:"template_id"` // 巡检模板ID
		GroupCode   string         `db:"group_code"`  // 巡检分组编码
		GroupName   string         `db:"group_name"`  // 巡检分组名称
		Description string         `db:"description"` // 巡检分组描述
		Enabled     int64          `db:"enabled"`     // 是否启用
		OrderNum    int64          `db:"order_num"`   // 排序号
		ConfigJson  sql.NullString `db:"config_json"` // 巡检分组扩展配置JSON
		CreatedBy   string         `db:"created_by"`  // 记录创建人
		UpdatedBy   string         `db:"updated_by"`  // 记录最后更新人
		CreatedAt   time.Time      `db:"created_at"`  // 记录创建时间
		UpdatedAt   time.Time      `db:"updated_at"`  // 记录更新时间
		IsDeleted   int64          `db:"is_deleted"`  // 是否已删除，软删除标记
	}
)

func newOnecInspectionGroupModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecInspectionGroupModel {
	return &defaultOnecInspectionGroupModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_inspection_group`",
	}
}

func (m *defaultOnecInspectionGroupModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, id)
	kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, data.TemplateId, data.GroupCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionGroupIdKey, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey)
	return err
}

func (m *defaultOnecInspectionGroupModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, id)
	kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, data.TemplateId, data.GroupCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionGroupIdKey, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey)
	return err
}

func (m *defaultOnecInspectionGroupModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecInspectionGroupModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, id)
		kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, data.TemplateId, data.GroupCode)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionGroupIdKey, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultOnecInspectionGroupModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, id)
		kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, data.TemplateId, data.GroupCode)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionGroupIdKey, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultOnecInspectionGroupModel) FindOne(ctx context.Context, id uint64) (*OnecInspectionGroup, error) {
	kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, id)
	var resp OnecInspectionGroup
	err := m.QueryRowCtx(ctx, &resp, kubeNovaOnecInspectionGroupIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionGroupRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionGroupModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionGroup, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecInspectionGroup
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*OnecInspectionGroup{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecInspectionGroupRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecInspectionGroupModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionGroup, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecInspectionGroupRows, m.table, where, orderStr)
	var resp []*OnecInspectionGroup

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*OnecInspectionGroup{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*OnecInspectionGroup{}, nil
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionGroupModel) FindOneByTemplateIdGroupCode(ctx context.Context, templateId uint64, groupCode string) (*OnecInspectionGroup, error) {
	kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, templateId, groupCode)
	var resp OnecInspectionGroup
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `template_id` = ? and `group_code` = ? limit 1", onecInspectionGroupRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, templateId, groupCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionGroupModel) Insert(ctx context.Context, data *OnecInspectionGroup) (sql.Result, error) {
	kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, data.Id)
	kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, data.TemplateId, data.GroupCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecInspectionGroupRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TemplateId, data.GroupCode, data.GroupName, data.Description, data.Enabled, data.OrderNum, data.ConfigJson, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaOnecInspectionGroupIdKey, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey)
	return ret, err
}

func (m *defaultOnecInspectionGroupModel) Update(ctx context.Context, newData *OnecInspectionGroup) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaOnecInspectionGroupIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, data.Id)
	kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecInspectionGroupTemplateIdGroupCodePrefix, data.TemplateId, data.GroupCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecInspectionGroupRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TemplateId, newData.GroupCode, newData.GroupName, newData.Description, newData.Enabled, newData.OrderNum, newData.ConfigJson, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeNovaOnecInspectionGroupIdKey, kubeNovaOnecInspectionGroupTemplateIdGroupCodeKey)
	return err
}

func (m *defaultOnecInspectionGroupModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionGroupIdPrefix, primary)
}

func (m *defaultOnecInspectionGroupModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionGroupRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecInspectionGroupModel) tableName() string {
	return m.table
}
