// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecClusterNodeFieldNames          = builder.RawFieldNames(&OnecClusterNode{})
	onecClusterNodeRows                = strings.Join(onecClusterNodeFieldNames, ",")
	onecClusterNodeRowsExpectAutoSet   = strings.Join(stringx.Remove(onecClusterNodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecClusterNodeRowsWithPlaceHolder = strings.Join(stringx.Remove(onecClusterNodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsOnecClusterNodeIdPrefix              = "cache:ikubeops:onecClusterNode:id:"
	cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix = "cache:ikubeops:onecClusterNode:clusterUuid:name:"
	cacheIkubeopsOnecClusterNodeNodeUuidPrefix        = "cache:ikubeops:onecClusterNode:nodeUuid:"
)

type (
	onecClusterNodeModel interface {
		Insert(ctx context.Context, data *OnecClusterNode) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*OnecClusterNode, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecClusterNode, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecClusterNode, error)
		FindOneByClusterUuidName(ctx context.Context, clusterUuid string, name string) (*OnecClusterNode, error)
		FindOneByNodeUuid(ctx context.Context, nodeUuid string) (*OnecClusterNode, error)
		Update(ctx context.Context, data *OnecClusterNode) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecClusterNodeModel struct {
		sqlc.CachedConn
		table string
	}

	OnecClusterNode struct {
		Id              uint64    `db:"id"`               // 自增主键
		ClusterUuid     string    `db:"cluster_uuid"`     // 所属集群ID
		NodeUuid        string    `db:"node_uuid"`        // 节点UID，唯一标识
		Name            string    `db:"name"`             // 节点名称，在同一集群中唯一
		Hostname        string    `db:"hostname"`         // 主机名
		Roles           string    `db:"roles"`            // 节点角色列表
		OsImage         string    `db:"os_image"`         // 操作系统
		NodeIp          string    `db:"node_ip"`          // 节点地址
		KernelVersion   string    `db:"kernel_version"`   // 内核版本
		OperatingSystem string    `db:"operating_system"` // 操作系统类型
		Architecture    string    `db:"architecture"`     // 架构类型
		Cpu             float64   `db:"cpu"`              // CPU核数
		Memory          float64   `db:"memory"`           // 内存大小，GiB
		Pods            int64     `db:"pods"`             // 最大Pod数量
		IsGpu           int64     `db:"is_gpu"`           // 节点是否包含GPU
		Runtime         string    `db:"runtime"`          // 容器运行时
		JoinAt          time.Time `db:"join_at"`          // 节点加入集群时间
		Unschedulable   int64     `db:"unschedulable"`    // 节点是否不可调度（1：可调度，2：不可调度）
		KubeletVersion  string    `db:"kubelet_version"`  // Kubelet版本
		Status          string    `db:"status"`           // 节点状态
		PodCidr         string    `db:"pod_cidr"`         // Pod CIDR
		PodCidrs        string    `db:"pod_cidrs"`        // Pod CIDRs
		CreatedBy       string    `db:"created_by"`       // 记录创建人
		UpdatedBy       string    `db:"updated_by"`       // 记录更新人
		CreatedAt       time.Time `db:"created_at"`       // 记录创建时间
		UpdatedAt       time.Time `db:"updated_at"`       // 记录更新时间
		IsDeleted       int64     `db:"is_deleted"`       // 是否删除
	}
)

func newOnecClusterNodeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecClusterNodeModel {
	return &defaultOnecClusterNodeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_cluster_node`",
	}
}

func (m *defaultOnecClusterNodeModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, data.ClusterUuid, data.Name)
	ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, id)
	ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, data.NodeUuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsOnecClusterNodeClusterUuidNameKey, ikubeopsOnecClusterNodeIdKey, ikubeopsOnecClusterNodeNodeUuidKey)
	return err
}

func (m *defaultOnecClusterNodeModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, data.ClusterUuid, data.Name)
	ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, id)
	ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, data.NodeUuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsOnecClusterNodeClusterUuidNameKey, ikubeopsOnecClusterNodeIdKey, ikubeopsOnecClusterNodeNodeUuidKey)
	return err
}

func (m *defaultOnecClusterNodeModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecClusterNodeModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, data.ClusterUuid, data.Name)
		ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, id)
		ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, data.NodeUuid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsOnecClusterNodeClusterUuidNameKey, ikubeopsOnecClusterNodeIdKey, ikubeopsOnecClusterNodeNodeUuidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultOnecClusterNodeModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, data.ClusterUuid, data.Name)
		ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, id)
		ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, data.NodeUuid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsOnecClusterNodeClusterUuidNameKey, ikubeopsOnecClusterNodeIdKey, ikubeopsOnecClusterNodeNodeUuidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultOnecClusterNodeModel) FindOne(ctx context.Context, id uint64) (*OnecClusterNode, error) {
	ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, id)
	var resp OnecClusterNode
	err := m.QueryRowCtx(ctx, &resp, ikubeopsOnecClusterNodeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecClusterNodeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterNodeModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecClusterNode, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecClusterNode
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecClusterNodeRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecClusterNodeModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecClusterNode, error) {
	// 处理 nil 参数
	if args == nil {
		args = []any{}
	}
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecClusterNodeRows, m.table, where, orderStr)
	var resp []*OnecClusterNode
	// 根据是否有参数来调用
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultOnecClusterNodeModel) FindOneByClusterUuidName(ctx context.Context, clusterUuid string, name string) (*OnecClusterNode, error) {
	ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, clusterUuid, name)
	var resp OnecClusterNode
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsOnecClusterNodeClusterUuidNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `cluster_uuid` = ? and `name` = ? AND `is_deleted` = 0  limit 1", onecClusterNodeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, clusterUuid, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterNodeModel) FindOneByNodeUuid(ctx context.Context, nodeUuid string) (*OnecClusterNode, error) {
	ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, nodeUuid)
	var resp OnecClusterNode
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsOnecClusterNodeNodeUuidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `node_uuid` = ? AND `is_deleted` = 0  limit 1", onecClusterNodeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, nodeUuid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterNodeModel) Insert(ctx context.Context, data *OnecClusterNode) (sql.Result, error) {
	ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, data.ClusterUuid, data.Name)
	ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, data.Id)
	ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, data.NodeUuid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecClusterNodeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClusterUuid, data.NodeUuid, data.Name, data.Hostname, data.Roles, data.OsImage, data.NodeIp, data.KernelVersion, data.OperatingSystem, data.Architecture, data.Cpu, data.Memory, data.Pods, data.IsGpu, data.Runtime, data.JoinAt, data.Unschedulable, data.KubeletVersion, data.Status, data.PodCidr, data.PodCidrs, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, ikubeopsOnecClusterNodeClusterUuidNameKey, ikubeopsOnecClusterNodeIdKey, ikubeopsOnecClusterNodeNodeUuidKey)
	return ret, err
}

func (m *defaultOnecClusterNodeModel) Update(ctx context.Context, newData *OnecClusterNode) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsOnecClusterNodeClusterUuidNameKey := fmt.Sprintf("%s%v:%v", cacheIkubeopsOnecClusterNodeClusterUuidNamePrefix, data.ClusterUuid, data.Name)
	ikubeopsOnecClusterNodeIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, data.Id)
	ikubeopsOnecClusterNodeNodeUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeNodeUuidPrefix, data.NodeUuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecClusterNodeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ClusterUuid, newData.NodeUuid, newData.Name, newData.Hostname, newData.Roles, newData.OsImage, newData.NodeIp, newData.KernelVersion, newData.OperatingSystem, newData.Architecture, newData.Cpu, newData.Memory, newData.Pods, newData.IsGpu, newData.Runtime, newData.JoinAt, newData.Unschedulable, newData.KubeletVersion, newData.Status, newData.PodCidr, newData.PodCidrs, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, ikubeopsOnecClusterNodeClusterUuidNameKey, ikubeopsOnecClusterNodeIdKey, ikubeopsOnecClusterNodeNodeUuidKey)
	return err
}

func (m *defaultOnecClusterNodeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterNodeIdPrefix, primary)
}

func (m *defaultOnecClusterNodeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecClusterNodeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecClusterNodeModel) tableName() string {
	return m.table
}
