// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecClusterResourceFieldNames          = builder.RawFieldNames(&OnecClusterResource{})
	onecClusterResourceRows                = strings.Join(onecClusterResourceFieldNames, ",")
	onecClusterResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(onecClusterResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecClusterResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(onecClusterResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsOnecClusterResourceIdPrefix          = "cache:ikubeops:onecClusterResource:id:"
	cacheIkubeopsOnecClusterResourceClusterUuidPrefix = "cache:ikubeops:onecClusterResource:clusterUuid:"
)

type (
	onecClusterResourceModel interface {
		Insert(ctx context.Context, data *OnecClusterResource) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*OnecClusterResource, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecClusterResource, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecClusterResource, error)
		FindOneByClusterUuid(ctx context.Context, clusterUuid string) (*OnecClusterResource, error)
		Update(ctx context.Context, data *OnecClusterResource) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecClusterResourceModel struct {
		sqlc.CachedConn
		table string
	}

	OnecClusterResource struct {
		Id                      uint64  `db:"id"`                        // 自增主键
		ClusterUuid             string  `db:"cluster_uuid"`              // 关联的集群UUID
		CpuPhysicalCapacity     float64 `db:"cpu_physical_capacity"`     // CPU物理总容量（核数）
		CpuAllocatedTotal       float64 `db:"cpu_allocated_total"`       // CPU实际分配总量（所有project_cluster表cpu_limit的总和）
		CpuCapacityTotal        float64 `db:"cpu_capacity_total"`        // CPU超分后总容量（所有project_cluster表cpu_capacity的总和）
		MemPhysicalCapacity     float64 `db:"mem_physical_capacity"`     // 内存物理总容量（GiB）
		MemAllocatedTotal       float64 `db:"mem_allocated_total"`       // 内存实际分配总量（所有project_cluster表mem_limit的总和）
		MemCapacityTotal        float64 `db:"mem_capacity_total"`        // 内存超分后总容量（所有project_cluster表mem_capacity的总和）
		StoragePhysicalCapacity float64 `db:"storage_physical_capacity"` // 存储物理总容量（GiB）
		StorageAllocatedTotal   float64 `db:"storage_allocated_total"`   // 存储分配总量（所有project_cluster表storage_limit的总和）
		GpuPhysicalCapacity     float64 `db:"gpu_physical_capacity"`     // GPU物理总容量（个）
		GpuAllocatedTotal       float64 `db:"gpu_allocated_total"`       // GPU实际分配总量（所有project_cluster表gpu_limit的总和）
		GpuCapacityTotal        float64 `db:"gpu_capacity_total"`        // GPU超分后总容量（所有project_cluster表gpu_capacity的总和）
		PodsPhysicalCapacity    int64   `db:"pods_physical_capacity"`    // Pod物理总容量（个）
		PodsAllocatedTotal      int64   `db:"pods_allocated_total"`      // Pod分配总量（所有project_cluster表pods_limit的总和）
		IsDeleted               int64   `db:"is_deleted"`                // 是否已删除，软删除标记
	}
)

func newOnecClusterResourceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecClusterResourceModel {
	return &defaultOnecClusterResourceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_cluster_resource`",
	}
}

func (m *defaultOnecClusterResourceModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, data.ClusterUuid)
	ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsOnecClusterResourceClusterUuidKey, ikubeopsOnecClusterResourceIdKey)
	return err
}

func (m *defaultOnecClusterResourceModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, data.ClusterUuid)
	ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsOnecClusterResourceClusterUuidKey, ikubeopsOnecClusterResourceIdKey)
	return err
}

func (m *defaultOnecClusterResourceModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecClusterResourceModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, data.ClusterUuid)
		ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsOnecClusterResourceClusterUuidKey, ikubeopsOnecClusterResourceIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultOnecClusterResourceModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, data.ClusterUuid)
		ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsOnecClusterResourceClusterUuidKey, ikubeopsOnecClusterResourceIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultOnecClusterResourceModel) FindOne(ctx context.Context, id uint64) (*OnecClusterResource, error) {
	ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, id)
	var resp OnecClusterResource
	err := m.QueryRowCtx(ctx, &resp, ikubeopsOnecClusterResourceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecClusterResourceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterResourceModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecClusterResource, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecClusterResource
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecClusterResourceRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecClusterResourceModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecClusterResource, error) {
	// 处理 nil 参数
	if args == nil {
		args = []any{}
	}
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecClusterResourceRows, m.table, where, orderStr)
	var resp []*OnecClusterResource
	// 根据是否有参数来调用
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultOnecClusterResourceModel) FindOneByClusterUuid(ctx context.Context, clusterUuid string) (*OnecClusterResource, error) {
	ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, clusterUuid)
	var resp OnecClusterResource
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsOnecClusterResourceClusterUuidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `cluster_uuid` = ? AND `is_deleted` = 0  limit 1", onecClusterResourceRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, clusterUuid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterResourceModel) Insert(ctx context.Context, data *OnecClusterResource) (sql.Result, error) {
	ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, data.ClusterUuid)
	ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecClusterResourceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClusterUuid, data.CpuPhysicalCapacity, data.CpuAllocatedTotal, data.CpuCapacityTotal, data.MemPhysicalCapacity, data.MemAllocatedTotal, data.MemCapacityTotal, data.StoragePhysicalCapacity, data.StorageAllocatedTotal, data.GpuPhysicalCapacity, data.GpuAllocatedTotal, data.GpuCapacityTotal, data.PodsPhysicalCapacity, data.PodsAllocatedTotal, data.IsDeleted)
	}, ikubeopsOnecClusterResourceClusterUuidKey, ikubeopsOnecClusterResourceIdKey)
	return ret, err
}

func (m *defaultOnecClusterResourceModel) Update(ctx context.Context, newData *OnecClusterResource) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsOnecClusterResourceClusterUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceClusterUuidPrefix, data.ClusterUuid)
	ikubeopsOnecClusterResourceIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecClusterResourceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ClusterUuid, newData.CpuPhysicalCapacity, newData.CpuAllocatedTotal, newData.CpuCapacityTotal, newData.MemPhysicalCapacity, newData.MemAllocatedTotal, newData.MemCapacityTotal, newData.StoragePhysicalCapacity, newData.StorageAllocatedTotal, newData.GpuPhysicalCapacity, newData.GpuAllocatedTotal, newData.GpuCapacityTotal, newData.PodsPhysicalCapacity, newData.PodsAllocatedTotal, newData.IsDeleted, newData.Id)
	}, ikubeopsOnecClusterResourceClusterUuidKey, ikubeopsOnecClusterResourceIdKey)
	return err
}

func (m *defaultOnecClusterResourceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsOnecClusterResourceIdPrefix, primary)
}

func (m *defaultOnecClusterResourceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecClusterResourceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecClusterResourceModel) tableName() string {
	return m.table
}
