// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecInspectionResultFieldNames          = builder.RawFieldNames(&OnecInspectionResult{})
	onecInspectionResultRows                = strings.Join(onecInspectionResultFieldNames, ",")
	onecInspectionResultRowsExpectAutoSet   = strings.Join(stringx.Remove(onecInspectionResultFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecInspectionResultRowsWithPlaceHolder = strings.Join(stringx.Remove(onecInspectionResultFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaOnecInspectionResultIdPrefix = "cache:kubeNova:onecInspectionResult:id:"
)

type (
	onecInspectionResultModel interface {
		Insert(ctx context.Context, data *OnecInspectionResult) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OnecInspectionResult, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionResult, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionResult, error)
		Update(ctx context.Context, data *OnecInspectionResult) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecInspectionResultModel struct {
		sqlc.CachedConn
		table string
	}

	OnecInspectionResult struct {
		Id         uint64         `db:"id"`          // 主键ID
		RecordId   uint64         `db:"record_id"`   // 巡检记录ID
		ItemId     uint64         `db:"item_id"`     // 巡检项ID
		ItemCode   string         `db:"item_code"`   // 巡检项编码
		ItemName   string         `db:"item_name"`   // 巡检项名称
		Category   string         `db:"category"`    // 巡检分类
		TargetType string         `db:"target_type"` // 目标类型
		TargetName string         `db:"target_name"` // 目标名称
		Severity   string         `db:"severity"`    // 严重级别
		Status     string         `db:"status"`      // 结果状态：success/warning/critical/failed
		Score      float64        `db:"score"`       // 巡检项得分
		Expected   string         `db:"expected"`    // 期望结果
		Actual     string         `db:"actual"`      // 实际结果
		Value      string         `db:"value"`       // 指标值
		Unit       string         `db:"unit"`        // 指标单位
		Message    string         `db:"message"`     // 结果说明
		Suggestion string         `db:"suggestion"`  // 处理建议
		DetailJson sql.NullString `db:"detail_json"` // 结果明细JSON
		CreatedBy  string         `db:"created_by"`  // 记录创建人
		UpdatedBy  string         `db:"updated_by"`  // 记录最后更新人
		CreatedAt  time.Time      `db:"created_at"`  // 记录创建时间
		UpdatedAt  time.Time      `db:"updated_at"`  // 记录更新时间
		IsDeleted  int64          `db:"is_deleted"`  // 是否已删除，软删除标记
	}
)

func newOnecInspectionResultModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecInspectionResultModel {
	return &defaultOnecInspectionResultModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_inspection_result`",
	}
}

func (m *defaultOnecInspectionResultModel) Delete(ctx context.Context, id uint64) error {
	kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionResultIdKey)
	return err
}

func (m *defaultOnecInspectionResultModel) DeleteSoft(ctx context.Context, id uint64) error {
	kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecInspectionResultIdKey)
	return err
}

func (m *defaultOnecInspectionResultModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecInspectionResultModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）

		// 处理缓存逻辑
		kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, id)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionResultIdKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultOnecInspectionResultModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）

		// 处理缓存逻辑
		kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, id)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecInspectionResultIdKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultOnecInspectionResultModel) FindOne(ctx context.Context, id uint64) (*OnecInspectionResult, error) {
	kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, id)
	var resp OnecInspectionResult
	err := m.QueryRowCtx(ctx, &resp, kubeNovaOnecInspectionResultIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionResultRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionResultModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecInspectionResult, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecInspectionResult
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*OnecInspectionResult{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecInspectionResultRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecInspectionResultModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecInspectionResult, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecInspectionResultRows, m.table, where, orderStr)
	var resp []*OnecInspectionResult

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*OnecInspectionResult{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*OnecInspectionResult{}, nil
	default:
		return nil, err
	}
}

func (m *defaultOnecInspectionResultModel) Insert(ctx context.Context, data *OnecInspectionResult) (sql.Result, error) {
	kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecInspectionResultRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RecordId, data.ItemId, data.ItemCode, data.ItemName, data.Category, data.TargetType, data.TargetName, data.Severity, data.Status, data.Score, data.Expected, data.Actual, data.Value, data.Unit, data.Message, data.Suggestion, data.DetailJson, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaOnecInspectionResultIdKey)
	return ret, err
}

func (m *defaultOnecInspectionResultModel) Update(ctx context.Context, data *OnecInspectionResult) error {
	kubeNovaOnecInspectionResultIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecInspectionResultRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.RecordId, data.ItemId, data.ItemCode, data.ItemName, data.Category, data.TargetType, data.TargetName, data.Severity, data.Status, data.Score, data.Expected, data.Actual, data.Value, data.Unit, data.Message, data.Suggestion, data.DetailJson, data.CreatedBy, data.UpdatedBy, data.IsDeleted, data.Id)
	}, kubeNovaOnecInspectionResultIdKey)
	return err
}

func (m *defaultOnecInspectionResultModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaOnecInspectionResultIdPrefix, primary)
}

func (m *defaultOnecInspectionResultModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecInspectionResultRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecInspectionResultModel) tableName() string {
	return m.table
}
