// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecLogAlertEvalStateFieldNames          = builder.RawFieldNames(&OnecLogAlertEvalState{})
	onecLogAlertEvalStateRows                = strings.Join(onecLogAlertEvalStateFieldNames, ",")
	onecLogAlertEvalStateRowsExpectAutoSet   = strings.Join(stringx.Remove(onecLogAlertEvalStateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecLogAlertEvalStateRowsWithPlaceHolder = strings.Join(stringx.Remove(onecLogAlertEvalStateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeNovaOnecLogAlertEvalStateIdPrefix                = "cache:kubeNova:onecLogAlertEvalState:id:"
	cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix = "cache:kubeNova:onecLogAlertEvalState:ruleId:clusterUuid:"
)

type (
	onecLogAlertEvalStateModel interface {
		Insert(ctx context.Context, data *OnecLogAlertEvalState) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OnecLogAlertEvalState, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecLogAlertEvalState, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecLogAlertEvalState, error)
		FindOneByRuleIdClusterUuid(ctx context.Context, ruleId uint64, clusterUuid string) (*OnecLogAlertEvalState, error)
		Update(ctx context.Context, data *OnecLogAlertEvalState) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecLogAlertEvalStateModel struct {
		sqlc.CachedConn
		table string
	}

	OnecLogAlertEvalState struct {
		Id              uint64         `db:"id"`               // 主键ID
		RuleId          uint64         `db:"rule_id"`          // 规则ID
		ClusterUuid     string         `db:"cluster_uuid"`     // 集群UUID
		CheckpointAt    int64          `db:"checkpoint_at"`    // 上次处理时间戳(毫秒)
		LastHitCount    int64          `db:"last_hit_count"`   // 上次命中数量
		ConsecutiveHits int64          `db:"consecutive_hits"` // 连续命中次数
		ConsecutiveMiss int64          `db:"consecutive_miss"` // 连续未命中次数
		StateJson       sql.NullString `db:"state_json"`       // 扩展状态JSON
		CreatedBy       string         `db:"created_by"`       // 记录创建人
		UpdatedBy       string         `db:"updated_by"`       // 记录最后更新人
		CreatedAt       time.Time      `db:"created_at"`       // 记录创建时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 记录更新时间
		IsDeleted       int64          `db:"is_deleted"`       // 是否已删除，软删除标记
	}
)

func newOnecLogAlertEvalStateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecLogAlertEvalStateModel {
	return &defaultOnecLogAlertEvalStateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_log_alert_eval_state`",
	}
}

func (m *defaultOnecLogAlertEvalStateModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, id)
	kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, data.RuleId, data.ClusterUuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecLogAlertEvalStateIdKey, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey)
	return err
}

func (m *defaultOnecLogAlertEvalStateModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, id)
	kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, data.RuleId, data.ClusterUuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeNovaOnecLogAlertEvalStateIdKey, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey)
	return err
}

func (m *defaultOnecLogAlertEvalStateModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecLogAlertEvalStateModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, id)
		kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, data.RuleId, data.ClusterUuid)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecLogAlertEvalStateIdKey, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey)

	}

	// 如果 id 为零值，直接通过 session 执行 SQL（无需处理缓存）
	return session.ExecCtx(ctx, query, args...)
}

func (m *defaultOnecLogAlertEvalStateModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 校验 SQL 字符串是否包含表名占位符
	// 如果没有 {table} 占位符，直接使用原始 SQL（兼容直接写表名的情况）
	var query string
	if strings.Contains(sqlStr, "{table}") {
		query = strings.ReplaceAll(sqlStr, "{table}", m.table)
	} else {
		query = sqlStr
	}

	// 如果 id 不为零值并且需要处理缓存逻辑
	if !isZeroValue(id) {

		// 查询数据以获取缓存键（如果需要）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 处理缓存逻辑
		kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, id)
		kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, data.RuleId, data.ClusterUuid)
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeNovaOnecLogAlertEvalStateIdKey, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey)

	}

	// 如果 id 为零值，直接执行 SQL（无需处理缓存）

	return m.ExecNoCacheCtx(ctx, query, args...)

}

func (m *defaultOnecLogAlertEvalStateModel) FindOne(ctx context.Context, id uint64) (*OnecLogAlertEvalState, error) {
	kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, id)
	var resp OnecLogAlertEvalState
	err := m.QueryRowCtx(ctx, &resp, kubeNovaOnecLogAlertEvalStateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecLogAlertEvalStateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecLogAlertEvalStateModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecLogAlertEvalState, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 is_deleted = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	// 只允许字母、数字、下划线，并移除危险字符
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符：分号、注释符号、引号等
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecLogAlertEvalState
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	// 搜索无结果是正常情况，返回空切片而非错误
	// 这样上层调用方可以直接判断切片长度，无需额外处理错误
	if total == 0 {
		return []*OnecLogAlertEvalState{}, 0, nil
	}
	offset := (page - 1) * pageSize

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecLogAlertEvalStateRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecLogAlertEvalStateModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecLogAlertEvalState, error) {
	// 处理 nil 参数，确保后续操作安全
	if args == nil {
		args = []any{}
	}

	// 初始化 WHERE 子句，根据数据库类型选择正确的引用符号

	where := "WHERE `is_deleted` = 0"

	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {

		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)

		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 安全处理排序字段，防止 SQL 注入
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		// 移除可能的 SQL 注入字符
		orderStr = strings.NewReplacer(
			";", "",
			"--", "",
			"/*", "",
			"*/", "",
			"'", "",
			"\"", "",
			"\\", "",
		).Replace(orderStr)

		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecLogAlertEvalStateRows, m.table, where, orderStr)
	var resp []*OnecLogAlertEvalState

	// 根据是否有参数来调用，避免传递空参数导致问题
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}

	switch err {
	case nil:
		// 返回结果，如果无数据则返回空切片
		if resp == nil {
			return []*OnecLogAlertEvalState{}, nil
		}
		return resp, nil
	case sqlx.ErrNotFound:
		// 无数据时返回空切片而非错误，保持与 Search 方法一致的行为
		return []*OnecLogAlertEvalState{}, nil
	default:
		return nil, err
	}
}

func (m *defaultOnecLogAlertEvalStateModel) FindOneByRuleIdClusterUuid(ctx context.Context, ruleId uint64, clusterUuid string) (*OnecLogAlertEvalState, error) {
	kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, ruleId, clusterUuid)
	var resp OnecLogAlertEvalState
	err := m.QueryRowIndexCtx(ctx, &resp, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `rule_id` = ? and `cluster_uuid` = ? limit 1", onecLogAlertEvalStateRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, ruleId, clusterUuid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecLogAlertEvalStateModel) Insert(ctx context.Context, data *OnecLogAlertEvalState) (sql.Result, error) {
	kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, data.Id)
	kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, data.RuleId, data.ClusterUuid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecLogAlertEvalStateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RuleId, data.ClusterUuid, data.CheckpointAt, data.LastHitCount, data.ConsecutiveHits, data.ConsecutiveMiss, data.StateJson, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeNovaOnecLogAlertEvalStateIdKey, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey)
	return ret, err
}

func (m *defaultOnecLogAlertEvalStateModel) Update(ctx context.Context, newData *OnecLogAlertEvalState) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeNovaOnecLogAlertEvalStateIdKey := fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, data.Id)
	kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey := fmt.Sprintf("%s%v:%v", cacheKubeNovaOnecLogAlertEvalStateRuleIdClusterUuidPrefix, data.RuleId, data.ClusterUuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecLogAlertEvalStateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RuleId, newData.ClusterUuid, newData.CheckpointAt, newData.LastHitCount, newData.ConsecutiveHits, newData.ConsecutiveMiss, newData.StateJson, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeNovaOnecLogAlertEvalStateIdKey, kubeNovaOnecLogAlertEvalStateRuleIdClusterUuidKey)
	return err
}

func (m *defaultOnecLogAlertEvalStateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeNovaOnecLogAlertEvalStateIdPrefix, primary)
}

func (m *defaultOnecLogAlertEvalStateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", onecLogAlertEvalStateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecLogAlertEvalStateModel) tableName() string {
	return m.table
}
