// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecProjectApplicationFieldNames          = builder.RawFieldNames(&OnecProjectApplication{})
	onecProjectApplicationRows                = strings.Join(onecProjectApplicationFieldNames, ",")
	onecProjectApplicationRowsExpectAutoSet   = strings.Join(stringx.Remove(onecProjectApplicationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecProjectApplicationRowsWithPlaceHolder = strings.Join(stringx.Remove(onecProjectApplicationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsOnecProjectApplicationIdPrefix                            = "cache:ikubeops:onecProjectApplication:id:"
	cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix = "cache:ikubeops:onecProjectApplication:workspaceId:nameEn:resourceType:"
)

type (
	onecProjectApplicationModel interface {
		Insert(ctx context.Context, data *OnecProjectApplication) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*OnecProjectApplication, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecProjectApplication, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecProjectApplication, error)
		FindOneByWorkspaceIdNameEnResourceType(ctx context.Context, workspaceId uint64, nameEn string, resourceType string) (*OnecProjectApplication, error)
		Update(ctx context.Context, data *OnecProjectApplication) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecProjectApplicationModel struct {
		sqlc.CachedConn
		table string
	}

	OnecProjectApplication struct {
		Id           uint64    `db:"id"`
		WorkspaceId  uint64    `db:"workspace_id"`  // 工作空间ID
		NameCn       string    `db:"name_cn"`       // 服务中文名
		NameEn       string    `db:"name_en"`       // 服务英文名
		ResourceType string    `db:"resource_type"` // 服务类型
		Description  string    `db:"description"`   // 服务描述
		CreatedBy    string    `db:"created_by"`    // 记录创建人
		UpdatedBy    string    `db:"updated_by"`    // 记录最后更新人
		CreatedAt    time.Time `db:"created_at"`    // 记录创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 记录更新时间
		IsDeleted    int64     `db:"is_deleted"`    // 是否已删除，软删除标记
	}
)

func newOnecProjectApplicationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecProjectApplicationModel {
	return &defaultOnecProjectApplicationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_project_application`",
	}
}

func (m *defaultOnecProjectApplicationModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, id)
	ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, data.WorkspaceId, data.NameEn, data.ResourceType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsOnecProjectApplicationIdKey, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey)
	return err
}

func (m *defaultOnecProjectApplicationModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, id)
	ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, data.WorkspaceId, data.NameEn, data.ResourceType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsOnecProjectApplicationIdKey, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey)
	return err
}

func (m *defaultOnecProjectApplicationModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecProjectApplicationModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, id)
		ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, data.WorkspaceId, data.NameEn, data.ResourceType) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsOnecProjectApplicationIdKey, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultOnecProjectApplicationModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, id)
		ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, data.WorkspaceId, data.NameEn, data.ResourceType) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsOnecProjectApplicationIdKey, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultOnecProjectApplicationModel) FindOne(ctx context.Context, id uint64) (*OnecProjectApplication, error) {
	ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, id)
	var resp OnecProjectApplication
	err := m.QueryRowCtx(ctx, &resp, ikubeopsOnecProjectApplicationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecProjectApplicationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecProjectApplicationModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecProjectApplication, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecProjectApplication
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecProjectApplicationRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecProjectApplicationModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecProjectApplication, error) {
	// 处理 nil 参数
	if args == nil {
		args = []any{}
	}
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecProjectApplicationRows, m.table, where, orderStr)
	var resp []*OnecProjectApplication
	// 根据是否有参数来调用
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultOnecProjectApplicationModel) FindOneByWorkspaceIdNameEnResourceType(ctx context.Context, workspaceId uint64, nameEn string, resourceType string) (*OnecProjectApplication, error) {
	ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, workspaceId, nameEn, resourceType)
	var resp OnecProjectApplication
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `workspace_id` = ? and `name_en` = ? and `resource_type` = ? AND `is_deleted` = 0  limit 1", onecProjectApplicationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, workspaceId, nameEn, resourceType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecProjectApplicationModel) Insert(ctx context.Context, data *OnecProjectApplication) (sql.Result, error) {
	ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, data.Id)
	ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, data.WorkspaceId, data.NameEn, data.ResourceType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecProjectApplicationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.WorkspaceId, data.NameCn, data.NameEn, data.ResourceType, data.Description, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, ikubeopsOnecProjectApplicationIdKey, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey)
	return ret, err
}

func (m *defaultOnecProjectApplicationModel) Update(ctx context.Context, newData *OnecProjectApplication) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsOnecProjectApplicationIdKey := fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, data.Id)
	ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey := fmt.Sprintf("%s%v:%v:%v", cacheIkubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypePrefix, data.WorkspaceId, data.NameEn, data.ResourceType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecProjectApplicationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.WorkspaceId, newData.NameCn, newData.NameEn, newData.ResourceType, newData.Description, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, ikubeopsOnecProjectApplicationIdKey, ikubeopsOnecProjectApplicationWorkspaceIdNameEnResourceTypeKey)
	return err
}

func (m *defaultOnecProjectApplicationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsOnecProjectApplicationIdPrefix, primary)
}

func (m *defaultOnecProjectApplicationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecProjectApplicationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecProjectApplicationModel) tableName() string {
	return m.table
}
