// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: manager.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/manager-rpc/internal/logic/logservice"
	"github.com/yanshicheng/kube-nova/application/manager-rpc/internal/svc"
	"github.com/yanshicheng/kube-nova/application/manager-rpc/pb"
)

type LogServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLogServiceServer
}

func NewLogServiceServer(svcCtx *svc.ServiceContext) *LogServiceServer {
	return &LogServiceServer{
		svcCtx: svcCtx,
	}
}

// 日志范围解析与日志告警
func (s *LogServiceServer) ResolveLogScope(ctx context.Context, in *pb.ResolveLogScopeReq) (*pb.ResolveLogScopeResp, error) {
	l := logservicelogic.NewResolveLogScopeLogic(ctx, s.svcCtx)
	return l.ResolveLogScope(in)
}

func (s *LogServiceServer) QueryLogs(ctx context.Context, in *pb.QueryLogsReq) (*pb.QueryLogsResp, error) {
	l := logservicelogic.NewQueryLogsLogic(ctx, s.svcCtx)
	return l.QueryLogs(in)
}

func (s *LogServiceServer) GetLogQueryModeOptions(ctx context.Context, in *pb.LogQueryModeOptionsReq) (*pb.LogQueryModeOptionsResp, error) {
	l := logservicelogic.NewGetLogQueryModeOptionsLogic(ctx, s.svcCtx)
	return l.GetLogQueryModeOptions(in)
}

func (s *LogServiceServer) GetLogClusterConfig(ctx context.Context, in *pb.GetLogClusterConfigReq) (*pb.GetLogClusterConfigResp, error) {
	l := logservicelogic.NewGetLogClusterConfigLogic(ctx, s.svcCtx)
	return l.GetLogClusterConfig(in)
}

func (s *LogServiceServer) GetLogClusterSyncStatus(ctx context.Context, in *pb.GetLogClusterSyncStatusReq) (*pb.GetLogClusterSyncStatusResp, error) {
	l := logservicelogic.NewGetLogClusterSyncStatusLogic(ctx, s.svcCtx)
	return l.GetLogClusterSyncStatus(in)
}

func (s *LogServiceServer) GetLogAlertEngineStats(ctx context.Context, in *pb.GetLogAlertEngineStatsReq) (*pb.GetLogAlertEngineStatsResp, error) {
	l := logservicelogic.NewGetLogAlertEngineStatsLogic(ctx, s.svcCtx)
	return l.GetLogAlertEngineStats(in)
}

func (s *LogServiceServer) ManualRetryLogAlertEvent(ctx context.Context, in *pb.ManualRetryLogAlertEventReq) (*pb.ManualRetryLogAlertEventResp, error) {
	l := logservicelogic.NewManualRetryLogAlertEventLogic(ctx, s.svcCtx)
	return l.ManualRetryLogAlertEvent(in)
}

func (s *LogServiceServer) CloseLogAlertEvent(ctx context.Context, in *pb.CloseLogAlertEventReq) (*pb.CloseLogAlertEventResp, error) {
	l := logservicelogic.NewCloseLogAlertEventLogic(ctx, s.svcCtx)
	return l.CloseLogAlertEvent(in)
}

func (s *LogServiceServer) UpdateLogAlertEventReason(ctx context.Context, in *pb.UpdateLogAlertEventReasonReq) (*pb.UpdateLogAlertEventReasonResp, error) {
	l := logservicelogic.NewUpdateLogAlertEventReasonLogic(ctx, s.svcCtx)
	return l.UpdateLogAlertEventReason(in)
}

func (s *LogServiceServer) DeleteLogAlertEvent(ctx context.Context, in *pb.DeleteLogAlertEventReq) (*pb.DeleteLogAlertEventResp, error) {
	l := logservicelogic.NewDeleteLogAlertEventLogic(ctx, s.svcCtx)
	return l.DeleteLogAlertEvent(in)
}

func (s *LogServiceServer) SearchLogAlertEvents(ctx context.Context, in *pb.SearchLogAlertEventsReq) (*pb.SearchLogAlertEventsResp, error) {
	l := logservicelogic.NewSearchLogAlertEventsLogic(ctx, s.svcCtx)
	return l.SearchLogAlertEvents(in)
}

func (s *LogServiceServer) ListLogLabelKeys(ctx context.Context, in *pb.ListLogLabelKeysReq) (*pb.ListLogLabelKeysResp, error) {
	l := logservicelogic.NewListLogLabelKeysLogic(ctx, s.svcCtx)
	return l.ListLogLabelKeys(in)
}

func (s *LogServiceServer) ListLogLabelValues(ctx context.Context, in *pb.ListLogLabelValuesReq) (*pb.ListLogLabelValuesResp, error) {
	l := logservicelogic.NewListLogLabelValuesLogic(ctx, s.svcCtx)
	return l.ListLogLabelValues(in)
}

func (s *LogServiceServer) AddLogAlertRule(ctx context.Context, in *pb.AddLogAlertRuleReq) (*pb.AddLogAlertRuleResp, error) {
	l := logservicelogic.NewAddLogAlertRuleLogic(ctx, s.svcCtx)
	return l.AddLogAlertRule(in)
}

func (s *LogServiceServer) UpdateLogAlertRule(ctx context.Context, in *pb.UpdateLogAlertRuleReq) (*pb.UpdateLogAlertRuleResp, error) {
	l := logservicelogic.NewUpdateLogAlertRuleLogic(ctx, s.svcCtx)
	return l.UpdateLogAlertRule(in)
}

func (s *LogServiceServer) GetLogAlertRuleById(ctx context.Context, in *pb.GetLogAlertRuleByIdReq) (*pb.GetLogAlertRuleByIdResp, error) {
	l := logservicelogic.NewGetLogAlertRuleByIdLogic(ctx, s.svcCtx)
	return l.GetLogAlertRuleById(in)
}

func (s *LogServiceServer) DelLogAlertRule(ctx context.Context, in *pb.DelLogAlertRuleReq) (*pb.DelLogAlertRuleResp, error) {
	l := logservicelogic.NewDelLogAlertRuleLogic(ctx, s.svcCtx)
	return l.DelLogAlertRule(in)
}

func (s *LogServiceServer) ToggleLogAlertRule(ctx context.Context, in *pb.ToggleLogAlertRuleReq) (*pb.ToggleLogAlertRuleResp, error) {
	l := logservicelogic.NewToggleLogAlertRuleLogic(ctx, s.svcCtx)
	return l.ToggleLogAlertRule(in)
}

func (s *LogServiceServer) SearchLogAlertRule(ctx context.Context, in *pb.SearchLogAlertRuleReq) (*pb.SearchLogAlertRuleResp, error) {
	l := logservicelogic.NewSearchLogAlertRuleLogic(ctx, s.svcCtx)
	return l.SearchLogAlertRule(in)
}
