// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: devops-manager.proto

package pipelineconfigservice

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/devops-manager-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionTektonResourceReq             = pb.ActionTektonResourceReq
	AddProjectChannelReq                = pb.AddProjectChannelReq
	BatchUpdateTektonStepImageReq       = pb.BatchUpdateTektonStepImageReq
	BatchUpdateTektonStepImageResp      = pb.BatchUpdateTektonStepImageResp
	BindProjectChannelsReq              = pb.BindProjectChannelsReq
	ChannelGroupOption                  = pb.ChannelGroupOption
	ChannelGroupOptionsResp             = pb.ChannelGroupOptionsResp
	ChannelMappingFieldDependency       = pb.ChannelMappingFieldDependency
	ChannelMappingFieldOption           = pb.ChannelMappingFieldOption
	ChannelMappingFieldOptionsReq       = pb.ChannelMappingFieldOptionsReq
	ChannelMappingFieldOptionsResp      = pb.ChannelMappingFieldOptionsResp
	CompoundParamField                  = pb.CompoundParamField
	ConfigTypeTreeReq                   = pb.ConfigTypeTreeReq
	ConfigTypeTreeResp                  = pb.ConfigTypeTreeResp
	CreateChannelGroupReq               = pb.CreateChannelGroupReq
	CreateChannelReq                    = pb.CreateChannelReq
	CreateChannelTypeReq                = pb.CreateChannelTypeReq
	CreateConfigTypeReq                 = pb.CreateConfigTypeReq
	CreateCredentialReq                 = pb.CreateCredentialReq
	CreateHostReq                       = pb.CreateHostReq
	CreateJenkinsAgentReq               = pb.CreateJenkinsAgentReq
	CreatePipelineEnvironmentReq        = pb.CreatePipelineEnvironmentReq
	CreatePipelineTemplateReq           = pb.CreatePipelineTemplateReq
	CreateProjectConfigReq              = pb.CreateProjectConfigReq
	CreateProjectMavenConfigReq         = pb.CreateProjectMavenConfigReq
	CreateProjectReq                    = pb.CreateProjectReq
	CreateStepCategoryReq               = pb.CreateStepCategoryReq
	CreateStepChannelParamMappingReq    = pb.CreateStepChannelParamMappingReq
	CreateStepTemplateReq               = pb.CreateStepTemplateReq
	CreateSystemReq                     = pb.CreateSystemReq
	CredentialTypeOption                = pb.CredentialTypeOption
	CredentialTypeOptionsResp           = pb.CredentialTypeOptionsResp
	CredentialUsage                     = pb.CredentialUsage
	DeleteByIdReq                       = pb.DeleteByIdReq
	DeleteJenkinsCredentialSyncReq      = pb.DeleteJenkinsCredentialSyncReq
	DeleteTektonResourceReq             = pb.DeleteTektonResourceReq
	DeleteTektonSecretReq               = pb.DeleteTektonSecretReq
	DescribeTektonResourceReq           = pb.DescribeTektonResourceReq
	DescribeTektonResourceResp          = pb.DescribeTektonResourceResp
	DevopsChannel                       = pb.DevopsChannel
	DevopsChannelGroup                  = pb.DevopsChannelGroup
	DevopsChannelType                   = pb.DevopsChannelType
	DevopsCheckProjectDependenciesReq   = pb.DevopsCheckProjectDependenciesReq
	DevopsCheckProjectDependenciesResp  = pb.DevopsCheckProjectDependenciesResp
	DevopsConfigType                    = pb.DevopsConfigType
	DevopsCredential                    = pb.DevopsCredential
	DevopsHost                          = pb.DevopsHost
	DevopsJenkinsAgent                  = pb.DevopsJenkinsAgent
	DevopsPipelineEnvironment           = pb.DevopsPipelineEnvironment
	DevopsPipelineTemplate              = pb.DevopsPipelineTemplate
	DevopsProject                       = pb.DevopsProject
	DevopsProjectChannelBinding         = pb.DevopsProjectChannelBinding
	DevopsProjectConfig                 = pb.DevopsProjectConfig
	DevopsProjectDependency             = pb.DevopsProjectDependency
	DevopsProjectMavenConfig            = pb.DevopsProjectMavenConfig
	DevopsProjectMember                 = pb.DevopsProjectMember
	DevopsProjectMemberInput            = pb.DevopsProjectMemberInput
	DevopsStepCategory                  = pb.DevopsStepCategory
	DevopsStepParam                     = pb.DevopsStepParam
	DevopsStepTemplate                  = pb.DevopsStepTemplate
	DevopsSyncProjectDeletedReq         = pb.DevopsSyncProjectDeletedReq
	DevopsSyncProjectInfoReq            = pb.DevopsSyncProjectInfoReq
	DevopsSyncProjectMemberInput        = pb.DevopsSyncProjectMemberInput
	DevopsSyncProjectMembersReq         = pb.DevopsSyncProjectMembersReq
	DevopsSystem                        = pb.DevopsSystem
	DevopsTektonTaskParam               = pb.DevopsTektonTaskParam
	DevopsTektonTaskResult              = pb.DevopsTektonTaskResult
	DevopsTektonWorkspace               = pb.DevopsTektonWorkspace
	DynamicParamOption                  = pb.DynamicParamOption
	DynamicParamOptionsReq              = pb.DynamicParamOptionsReq
	DynamicParamOptionsResp             = pb.DynamicParamOptionsResp
	EmptyResp                           = pb.EmptyResp
	GetByIdReq                          = pb.GetByIdReq
	GetChannelGroupResp                 = pb.GetChannelGroupResp
	GetChannelResp                      = pb.GetChannelResp
	GetChannelTypeResp                  = pb.GetChannelTypeResp
	GetChannelVariableSpecsReq          = pb.GetChannelVariableSpecsReq
	GetChannelVariableSpecsResp         = pb.GetChannelVariableSpecsResp
	GetConfigTypeResp                   = pb.GetConfigTypeResp
	GetCredentialResp                   = pb.GetCredentialResp
	GetCredentialUsageResp              = pb.GetCredentialUsageResp
	GetHostResp                         = pb.GetHostResp
	GetJenkinsAgentResp                 = pb.GetJenkinsAgentResp
	GetPipelineEnvironmentResp          = pb.GetPipelineEnvironmentResp
	GetPipelineTemplateResp             = pb.GetPipelineTemplateResp
	GetProjectConfigResp                = pb.GetProjectConfigResp
	GetProjectMavenConfigResp           = pb.GetProjectMavenConfigResp
	GetProjectResp                      = pb.GetProjectResp
	GetStepCategoryResp                 = pb.GetStepCategoryResp
	GetStepTemplateResp                 = pb.GetStepTemplateResp
	GetSystemResp                       = pb.GetSystemResp
	GetTektonResourceReq                = pb.GetTektonResourceReq
	GetTektonResourceResp               = pb.GetTektonResourceResp
	GetTektonSecretReq                  = pb.GetTektonSecretReq
	GetTektonSecretResp                 = pb.GetTektonSecretResp
	IdResp                              = pb.IdResp
	JenkinsAgentContainer               = pb.JenkinsAgentContainer
	JenkinsCredentialMapping            = pb.JenkinsCredentialMapping
	JenkinsCredentialReference          = pb.JenkinsCredentialReference
	JenkinsCredentialReferenceReq       = pb.JenkinsCredentialReferenceReq
	JenkinsCredentialSyncRecord         = pb.JenkinsCredentialSyncRecord
	ListChannelGroupReq                 = pb.ListChannelGroupReq
	ListChannelGroupResp                = pb.ListChannelGroupResp
	ListChannelReq                      = pb.ListChannelReq
	ListChannelResp                     = pb.ListChannelResp
	ListChannelTypeReq                  = pb.ListChannelTypeReq
	ListChannelTypeResp                 = pb.ListChannelTypeResp
	ListConfigTypeReq                   = pb.ListConfigTypeReq
	ListConfigTypeResp                  = pb.ListConfigTypeResp
	ListCredentialReq                   = pb.ListCredentialReq
	ListCredentialResp                  = pb.ListCredentialResp
	ListHostReq                         = pb.ListHostReq
	ListHostResp                        = pb.ListHostResp
	ListJenkinsAgentReq                 = pb.ListJenkinsAgentReq
	ListJenkinsAgentResp                = pb.ListJenkinsAgentResp
	ListJenkinsCredentialReferencesResp = pb.ListJenkinsCredentialReferencesResp
	ListJenkinsCredentialSyncReq        = pb.ListJenkinsCredentialSyncReq
	ListJenkinsCredentialSyncResp       = pb.ListJenkinsCredentialSyncResp
	ListPipelineEnvironmentReq          = pb.ListPipelineEnvironmentReq
	ListPipelineEnvironmentResp         = pb.ListPipelineEnvironmentResp
	ListPipelineTemplateReq             = pb.ListPipelineTemplateReq
	ListPipelineTemplateResp            = pb.ListPipelineTemplateResp
	ListProjectChannelBindingReq        = pb.ListProjectChannelBindingReq
	ListProjectChannelBindingResp       = pb.ListProjectChannelBindingResp
	ListProjectConfigReq                = pb.ListProjectConfigReq
	ListProjectConfigResp               = pb.ListProjectConfigResp
	ListProjectMavenConfigReq           = pb.ListProjectMavenConfigReq
	ListProjectMavenConfigResp          = pb.ListProjectMavenConfigResp
	ListProjectMemberReq                = pb.ListProjectMemberReq
	ListProjectMemberResp               = pb.ListProjectMemberResp
	ListProjectReq                      = pb.ListProjectReq
	ListProjectResp                     = pb.ListProjectResp
	ListStepCategoryReq                 = pb.ListStepCategoryReq
	ListStepCategoryResp                = pb.ListStepCategoryResp
	ListStepChannelParamMappingReq      = pb.ListStepChannelParamMappingReq
	ListStepChannelParamMappingResp     = pb.ListStepChannelParamMappingResp
	ListStepTemplateReq                 = pb.ListStepTemplateReq
	ListStepTemplateResp                = pb.ListStepTemplateResp
	ListSystemReq                       = pb.ListSystemReq
	ListSystemResp                      = pb.ListSystemResp
	ListTektonPVCReq                    = pb.ListTektonPVCReq
	ListTektonPVCResp                   = pb.ListTektonPVCResp
	ListTektonResourceReq               = pb.ListTektonResourceReq
	ListTektonResourceResp              = pb.ListTektonResourceResp
	ListTektonSecretBindingReq          = pb.ListTektonSecretBindingReq
	ListTektonSecretBindingResp         = pb.ListTektonSecretBindingResp
	ListTektonSecretReq                 = pb.ListTektonSecretReq
	ListTektonSecretResp                = pb.ListTektonSecretResp
	ListTektonStepImageReq              = pb.ListTektonStepImageReq
	ListTektonStepImageResp             = pb.ListTektonStepImageResp
	LogTektonResourceReq                = pb.LogTektonResourceReq
	LogTektonResourceResp               = pb.LogTektonResourceResp
	PipelineArtifactUrlReq              = pb.PipelineArtifactUrlReq
	PipelineArtifactUrlResp             = pb.PipelineArtifactUrlResp
	PipelinePreviewResp                 = pb.PipelinePreviewResp
	PipelineTemplateStep                = pb.PipelineTemplateStep
	PipelineTemplateVariable            = pb.PipelineTemplateVariable
	PipelineTemplateVariablesResp       = pb.PipelineTemplateVariablesResp
	QueryDynamicOptionsReq              = pb.QueryDynamicOptionsReq
	QueryDynamicOptionsResp             = pb.QueryDynamicOptionsResp
	RenderOutputReq                     = pb.RenderOutputReq
	RenderOutputResp                    = pb.RenderOutputResp
	ResolveAddressReq                   = pb.ResolveAddressReq
	ResolveAddressResp                  = pb.ResolveAddressResp
	ResolveChannelBindingReq            = pb.ResolveChannelBindingReq
	ResolveChannelBindingResp           = pb.ResolveChannelBindingResp
	ResolveChannelCredentialValueReq    = pb.ResolveChannelCredentialValueReq
	ResolveChannelCredentialValueResp   = pb.ResolveChannelCredentialValueResp
	ResolveCredentialReq                = pb.ResolveCredentialReq
	ResolveCredentialResp               = pb.ResolveCredentialResp
	ResolveCredentialValueReq           = pb.ResolveCredentialValueReq
	ResolveCredentialValueResp          = pb.ResolveCredentialValueResp
	ResolveHostGroupTargetsReq          = pb.ResolveHostGroupTargetsReq
	ResolveHostGroupTargetsResp         = pb.ResolveHostGroupTargetsResp
	ResolveMavenConfigReq               = pb.ResolveMavenConfigReq
	ResolveMavenConfigResp              = pb.ResolveMavenConfigResp
	ResolvePipelineRuntimeReq           = pb.ResolvePipelineRuntimeReq
	ResolvePipelineRuntimeResp          = pb.ResolvePipelineRuntimeResp
	ResolveProjectConfigReq             = pb.ResolveProjectConfigReq
	ResolveProjectConfigResp            = pb.ResolveProjectConfigResp
	SavePipelineTemplateStepsReq        = pb.SavePipelineTemplateStepsReq
	SaveTektonResourceReq               = pb.SaveTektonResourceReq
	SaveTektonSecretReq                 = pb.SaveTektonSecretReq
	SetProjectMembersReq                = pb.SetProjectMembersReq
	StepArtifactConfig                  = pb.StepArtifactConfig
	StepChannelParamMappingItem         = pb.StepChannelParamMappingItem
	StepParamConfig                     = pb.StepParamConfig
	StepParamDependency                 = pb.StepParamDependency
	StepParamOption                     = pb.StepParamOption
	SyncJenkinsCredentialsReq           = pb.SyncJenkinsCredentialsReq
	SyncJenkinsCredentialsResp          = pb.SyncJenkinsCredentialsResp
	SyncTektonSecretReq                 = pb.SyncTektonSecretReq
	TektonPVC                           = pb.TektonPVC
	TektonPropertySpec                  = pb.TektonPropertySpec
	TektonResource                      = pb.TektonResource
	TektonSecret                        = pb.TektonSecret
	TektonSecretBindingOption           = pb.TektonSecretBindingOption
	TektonStepImageItem                 = pb.TektonStepImageItem
	TestChannelReq                      = pb.TestChannelReq
	TestChannelResp                     = pb.TestChannelResp
	TestHostReq                         = pb.TestHostReq
	UpdateChannelGroupReq               = pb.UpdateChannelGroupReq
	UpdateChannelReq                    = pb.UpdateChannelReq
	UpdateChannelTypeReq                = pb.UpdateChannelTypeReq
	UpdateConfigTypeReq                 = pb.UpdateConfigTypeReq
	UpdateCredentialReq                 = pb.UpdateCredentialReq
	UpdateHostReq                       = pb.UpdateHostReq
	UpdateJenkinsAgentReq               = pb.UpdateJenkinsAgentReq
	UpdatePipelineEnvironmentReq        = pb.UpdatePipelineEnvironmentReq
	UpdatePipelineTemplateReq           = pb.UpdatePipelineTemplateReq
	UpdateProjectChannelBindingReq      = pb.UpdateProjectChannelBindingReq
	UpdateProjectConfigReq              = pb.UpdateProjectConfigReq
	UpdateProjectMavenConfigReq         = pb.UpdateProjectMavenConfigReq
	UpdateProjectReq                    = pb.UpdateProjectReq
	UpdateStatusReq                     = pb.UpdateStatusReq
	UpdateStepCategoryReq               = pb.UpdateStepCategoryReq
	UpdateStepChannelParamMappingReq    = pb.UpdateStepChannelParamMappingReq
	UpdateStepTemplateReq               = pb.UpdateStepTemplateReq
	UpdateSystemReq                     = pb.UpdateSystemReq
	UpdateTektonStepImageItem           = pb.UpdateTektonStepImageItem
	UploadPipelineArtifactReq           = pb.UploadPipelineArtifactReq
	UploadPipelineArtifactResp          = pb.UploadPipelineArtifactResp
	ValidateVariableValuesReq           = pb.ValidateVariableValuesReq
	ValidateVariableValuesResp          = pb.ValidateVariableValuesResp
	VariableOption                      = pb.VariableOption
	VariableSpec                        = pb.VariableSpec

	PipelineConfigService interface {
		SystemCreate(ctx context.Context, in *CreateSystemReq, opts ...grpc.CallOption) (*IdResp, error)
		SystemUpdate(ctx context.Context, in *UpdateSystemReq, opts ...grpc.CallOption) (*EmptyResp, error)
		SystemDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		SystemGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetSystemResp, error)
		SystemList(ctx context.Context, in *ListSystemReq, opts ...grpc.CallOption) (*ListSystemResp, error)
		PipelineEnvironmentCreate(ctx context.Context, in *CreatePipelineEnvironmentReq, opts ...grpc.CallOption) (*IdResp, error)
		PipelineEnvironmentUpdate(ctx context.Context, in *UpdatePipelineEnvironmentReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PipelineEnvironmentDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PipelineEnvironmentGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetPipelineEnvironmentResp, error)
		PipelineEnvironmentList(ctx context.Context, in *ListPipelineEnvironmentReq, opts ...grpc.CallOption) (*ListPipelineEnvironmentResp, error)
		StepCategoryCreate(ctx context.Context, in *CreateStepCategoryReq, opts ...grpc.CallOption) (*IdResp, error)
		StepCategoryUpdate(ctx context.Context, in *UpdateStepCategoryReq, opts ...grpc.CallOption) (*EmptyResp, error)
		StepCategoryDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		StepCategoryGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetStepCategoryResp, error)
		StepCategoryList(ctx context.Context, in *ListStepCategoryReq, opts ...grpc.CallOption) (*ListStepCategoryResp, error)
		JenkinsStepCreate(ctx context.Context, in *CreateStepTemplateReq, opts ...grpc.CallOption) (*IdResp, error)
		JenkinsStepUpdate(ctx context.Context, in *UpdateStepTemplateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		JenkinsStepDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		JenkinsStepGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetStepTemplateResp, error)
		JenkinsStepList(ctx context.Context, in *ListStepTemplateReq, opts ...grpc.CallOption) (*ListStepTemplateResp, error)
		JenkinsStepStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*EmptyResp, error)
		TektonStepCreate(ctx context.Context, in *CreateStepTemplateReq, opts ...grpc.CallOption) (*IdResp, error)
		TektonStepUpdate(ctx context.Context, in *UpdateStepTemplateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		TektonStepDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		TektonStepGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetStepTemplateResp, error)
		TektonStepList(ctx context.Context, in *ListStepTemplateReq, opts ...grpc.CallOption) (*ListStepTemplateResp, error)
		TektonStepStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*EmptyResp, error)
		TektonStepImageList(ctx context.Context, in *ListTektonStepImageReq, opts ...grpc.CallOption) (*ListTektonStepImageResp, error)
		TektonStepImageBatchUpdate(ctx context.Context, in *BatchUpdateTektonStepImageReq, opts ...grpc.CallOption) (*BatchUpdateTektonStepImageResp, error)
		PipelineTemplateCreate(ctx context.Context, in *CreatePipelineTemplateReq, opts ...grpc.CallOption) (*IdResp, error)
		PipelineTemplateUpdate(ctx context.Context, in *UpdatePipelineTemplateReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PipelineTemplateDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PipelineTemplateGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetPipelineTemplateResp, error)
		PipelineTemplateList(ctx context.Context, in *ListPipelineTemplateReq, opts ...grpc.CallOption) (*ListPipelineTemplateResp, error)
		PipelineTemplateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PipelineTemplateStepsSave(ctx context.Context, in *SavePipelineTemplateStepsReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PipelineTemplatePreview(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*PipelinePreviewResp, error)
		PipelineTemplateVariables(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*PipelineTemplateVariablesResp, error)
		CredentialTypeOptions(ctx context.Context, in *EmptyResp, opts ...grpc.CallOption) (*CredentialTypeOptionsResp, error)
		ChannelGroupOptions(ctx context.Context, in *EmptyResp, opts ...grpc.CallOption) (*ChannelGroupOptionsResp, error)
		ChannelMappingFieldOptions(ctx context.Context, in *ChannelMappingFieldOptionsReq, opts ...grpc.CallOption) (*ChannelMappingFieldOptionsResp, error)
		ListStepChannelParamMapping(ctx context.Context, in *ListStepChannelParamMappingReq, opts ...grpc.CallOption) (*ListStepChannelParamMappingResp, error)
		CreateStepChannelParamMapping(ctx context.Context, in *CreateStepChannelParamMappingReq, opts ...grpc.CallOption) (*IdResp, error)
		UpdateStepChannelParamMapping(ctx context.Context, in *UpdateStepChannelParamMappingReq, opts ...grpc.CallOption) (*EmptyResp, error)
		DeleteStepChannelParamMapping(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		DynamicParamOptions(ctx context.Context, in *DynamicParamOptionsReq, opts ...grpc.CallOption) (*DynamicParamOptionsResp, error)
		JenkinsAgentCreate(ctx context.Context, in *CreateJenkinsAgentReq, opts ...grpc.CallOption) (*IdResp, error)
		JenkinsAgentUpdate(ctx context.Context, in *UpdateJenkinsAgentReq, opts ...grpc.CallOption) (*EmptyResp, error)
		JenkinsAgentDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error)
		JenkinsAgentGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetJenkinsAgentResp, error)
		JenkinsAgentList(ctx context.Context, in *ListJenkinsAgentReq, opts ...grpc.CallOption) (*ListJenkinsAgentResp, error)
		UploadPipelineArtifact(ctx context.Context, in *UploadPipelineArtifactReq, opts ...grpc.CallOption) (*UploadPipelineArtifactResp, error)
		PipelineArtifactUrl(ctx context.Context, in *PipelineArtifactUrlReq, opts ...grpc.CallOption) (*PipelineArtifactUrlResp, error)
		ResolvePipelineRuntime(ctx context.Context, in *ResolvePipelineRuntimeReq, opts ...grpc.CallOption) (*ResolvePipelineRuntimeResp, error)
		ResolveChannelBinding(ctx context.Context, in *ResolveChannelBindingReq, opts ...grpc.CallOption) (*ResolveChannelBindingResp, error)
		ResolveCredentialValue(ctx context.Context, in *ResolveCredentialValueReq, opts ...grpc.CallOption) (*ResolveCredentialValueResp, error)
		ResolveChannelCredentialValue(ctx context.Context, in *ResolveChannelCredentialValueReq, opts ...grpc.CallOption) (*ResolveChannelCredentialValueResp, error)
		ResolveMavenConfig(ctx context.Context, in *ResolveMavenConfigReq, opts ...grpc.CallOption) (*ResolveMavenConfigResp, error)
		ResolveProjectConfig(ctx context.Context, in *ResolveProjectConfigReq, opts ...grpc.CallOption) (*ResolveProjectConfigResp, error)
		ResolveHostGroupTargets(ctx context.Context, in *ResolveHostGroupTargetsReq, opts ...grpc.CallOption) (*ResolveHostGroupTargetsResp, error)
		SyncJenkinsCredentials(ctx context.Context, in *SyncJenkinsCredentialsReq, opts ...grpc.CallOption) (*SyncJenkinsCredentialsResp, error)
		JenkinsCredentialSyncList(ctx context.Context, in *ListJenkinsCredentialSyncReq, opts ...grpc.CallOption) (*ListJenkinsCredentialSyncResp, error)
		JenkinsCredentialReferences(ctx context.Context, in *JenkinsCredentialReferenceReq, opts ...grpc.CallOption) (*ListJenkinsCredentialReferencesResp, error)
		JenkinsCredentialSyncDelete(ctx context.Context, in *DeleteJenkinsCredentialSyncReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultPipelineConfigService struct {
		cli zrpc.Client
	}
)

func NewPipelineConfigService(cli zrpc.Client) PipelineConfigService {
	return &defaultPipelineConfigService{
		cli: cli,
	}
}

func (m *defaultPipelineConfigService) SystemCreate(ctx context.Context, in *CreateSystemReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.SystemCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) SystemUpdate(ctx context.Context, in *UpdateSystemReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.SystemUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) SystemDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.SystemDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) SystemGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetSystemResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.SystemGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) SystemList(ctx context.Context, in *ListSystemReq, opts ...grpc.CallOption) (*ListSystemResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.SystemList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineEnvironmentCreate(ctx context.Context, in *CreatePipelineEnvironmentReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineEnvironmentCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineEnvironmentUpdate(ctx context.Context, in *UpdatePipelineEnvironmentReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineEnvironmentUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineEnvironmentDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineEnvironmentDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineEnvironmentGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetPipelineEnvironmentResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineEnvironmentGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineEnvironmentList(ctx context.Context, in *ListPipelineEnvironmentReq, opts ...grpc.CallOption) (*ListPipelineEnvironmentResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineEnvironmentList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) StepCategoryCreate(ctx context.Context, in *CreateStepCategoryReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.StepCategoryCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) StepCategoryUpdate(ctx context.Context, in *UpdateStepCategoryReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.StepCategoryUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) StepCategoryDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.StepCategoryDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) StepCategoryGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetStepCategoryResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.StepCategoryGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) StepCategoryList(ctx context.Context, in *ListStepCategoryReq, opts ...grpc.CallOption) (*ListStepCategoryResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.StepCategoryList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsStepCreate(ctx context.Context, in *CreateStepTemplateReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsStepCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsStepUpdate(ctx context.Context, in *UpdateStepTemplateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsStepUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsStepDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsStepDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsStepGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetStepTemplateResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsStepGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsStepList(ctx context.Context, in *ListStepTemplateReq, opts ...grpc.CallOption) (*ListStepTemplateResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsStepList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsStepStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsStepStatus(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepCreate(ctx context.Context, in *CreateStepTemplateReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepUpdate(ctx context.Context, in *UpdateStepTemplateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetStepTemplateResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepList(ctx context.Context, in *ListStepTemplateReq, opts ...grpc.CallOption) (*ListStepTemplateResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepStatus(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepImageList(ctx context.Context, in *ListTektonStepImageReq, opts ...grpc.CallOption) (*ListTektonStepImageResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepImageList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) TektonStepImageBatchUpdate(ctx context.Context, in *BatchUpdateTektonStepImageReq, opts ...grpc.CallOption) (*BatchUpdateTektonStepImageResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.TektonStepImageBatchUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateCreate(ctx context.Context, in *CreatePipelineTemplateReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateUpdate(ctx context.Context, in *UpdatePipelineTemplateReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetPipelineTemplateResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateList(ctx context.Context, in *ListPipelineTemplateReq, opts ...grpc.CallOption) (*ListPipelineTemplateResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateStatus(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateStepsSave(ctx context.Context, in *SavePipelineTemplateStepsReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateStepsSave(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplatePreview(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*PipelinePreviewResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplatePreview(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineTemplateVariables(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*PipelineTemplateVariablesResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineTemplateVariables(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) CredentialTypeOptions(ctx context.Context, in *EmptyResp, opts ...grpc.CallOption) (*CredentialTypeOptionsResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.CredentialTypeOptions(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ChannelGroupOptions(ctx context.Context, in *EmptyResp, opts ...grpc.CallOption) (*ChannelGroupOptionsResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ChannelGroupOptions(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ChannelMappingFieldOptions(ctx context.Context, in *ChannelMappingFieldOptionsReq, opts ...grpc.CallOption) (*ChannelMappingFieldOptionsResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ChannelMappingFieldOptions(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ListStepChannelParamMapping(ctx context.Context, in *ListStepChannelParamMappingReq, opts ...grpc.CallOption) (*ListStepChannelParamMappingResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ListStepChannelParamMapping(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) CreateStepChannelParamMapping(ctx context.Context, in *CreateStepChannelParamMappingReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.CreateStepChannelParamMapping(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) UpdateStepChannelParamMapping(ctx context.Context, in *UpdateStepChannelParamMappingReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.UpdateStepChannelParamMapping(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) DeleteStepChannelParamMapping(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.DeleteStepChannelParamMapping(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) DynamicParamOptions(ctx context.Context, in *DynamicParamOptionsReq, opts ...grpc.CallOption) (*DynamicParamOptionsResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.DynamicParamOptions(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsAgentCreate(ctx context.Context, in *CreateJenkinsAgentReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsAgentCreate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsAgentUpdate(ctx context.Context, in *UpdateJenkinsAgentReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsAgentUpdate(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsAgentDelete(ctx context.Context, in *DeleteByIdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsAgentDelete(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsAgentGet(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetJenkinsAgentResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsAgentGet(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsAgentList(ctx context.Context, in *ListJenkinsAgentReq, opts ...grpc.CallOption) (*ListJenkinsAgentResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsAgentList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) UploadPipelineArtifact(ctx context.Context, in *UploadPipelineArtifactReq, opts ...grpc.CallOption) (*UploadPipelineArtifactResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.UploadPipelineArtifact(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) PipelineArtifactUrl(ctx context.Context, in *PipelineArtifactUrlReq, opts ...grpc.CallOption) (*PipelineArtifactUrlResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.PipelineArtifactUrl(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolvePipelineRuntime(ctx context.Context, in *ResolvePipelineRuntimeReq, opts ...grpc.CallOption) (*ResolvePipelineRuntimeResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolvePipelineRuntime(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolveChannelBinding(ctx context.Context, in *ResolveChannelBindingReq, opts ...grpc.CallOption) (*ResolveChannelBindingResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolveChannelBinding(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolveCredentialValue(ctx context.Context, in *ResolveCredentialValueReq, opts ...grpc.CallOption) (*ResolveCredentialValueResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolveCredentialValue(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolveChannelCredentialValue(ctx context.Context, in *ResolveChannelCredentialValueReq, opts ...grpc.CallOption) (*ResolveChannelCredentialValueResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolveChannelCredentialValue(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolveMavenConfig(ctx context.Context, in *ResolveMavenConfigReq, opts ...grpc.CallOption) (*ResolveMavenConfigResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolveMavenConfig(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolveProjectConfig(ctx context.Context, in *ResolveProjectConfigReq, opts ...grpc.CallOption) (*ResolveProjectConfigResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolveProjectConfig(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) ResolveHostGroupTargets(ctx context.Context, in *ResolveHostGroupTargetsReq, opts ...grpc.CallOption) (*ResolveHostGroupTargetsResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.ResolveHostGroupTargets(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) SyncJenkinsCredentials(ctx context.Context, in *SyncJenkinsCredentialsReq, opts ...grpc.CallOption) (*SyncJenkinsCredentialsResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.SyncJenkinsCredentials(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsCredentialSyncList(ctx context.Context, in *ListJenkinsCredentialSyncReq, opts ...grpc.CallOption) (*ListJenkinsCredentialSyncResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsCredentialSyncList(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsCredentialReferences(ctx context.Context, in *JenkinsCredentialReferenceReq, opts ...grpc.CallOption) (*ListJenkinsCredentialReferencesResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsCredentialReferences(ctx, in, opts...)
}

func (m *defaultPipelineConfigService) JenkinsCredentialSyncDelete(ctx context.Context, in *DeleteJenkinsCredentialSyncReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewPipelineConfigServiceClient(m.cli.Conn())
	return client.JenkinsCredentialSyncDelete(ctx, in, opts...)
}
