// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: devops-pipeline.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/devops-pipeline-rpc/internal/logic/executionservice"
	"github.com/yanshicheng/kube-nova/application/devops-pipeline-rpc/internal/svc"
	"github.com/yanshicheng/kube-nova/application/devops-pipeline-rpc/pb"
)

type ExecutionServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedExecutionServiceServer
}

func NewExecutionServiceServer(svcCtx *svc.ServiceContext) *ExecutionServiceServer {
	return &ExecutionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ExecutionServiceServer) Health(ctx context.Context, in *pb.HealthReq) (*pb.HealthResp, error) {
	l := executionservicelogic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}

func (s *ExecutionServiceServer) PipelineCreate(ctx context.Context, in *pb.CreatePipelineReq) (*pb.IdResp, error) {
	l := executionservicelogic.NewPipelineCreateLogic(ctx, s.svcCtx)
	return l.PipelineCreate(in)
}

func (s *ExecutionServiceServer) PipelineUpdate(ctx context.Context, in *pb.UpdatePipelineReq) (*pb.EmptyResp, error) {
	l := executionservicelogic.NewPipelineUpdateLogic(ctx, s.svcCtx)
	return l.PipelineUpdate(in)
}

func (s *ExecutionServiceServer) PipelineDelete(ctx context.Context, in *pb.DeletePipelineReq) (*pb.EmptyResp, error) {
	l := executionservicelogic.NewPipelineDeleteLogic(ctx, s.svcCtx)
	return l.PipelineDelete(in)
}

func (s *ExecutionServiceServer) PipelineGet(ctx context.Context, in *pb.GetPipelineReq) (*pb.GetPipelineResp, error) {
	l := executionservicelogic.NewPipelineGetLogic(ctx, s.svcCtx)
	return l.PipelineGet(in)
}

func (s *ExecutionServiceServer) PipelineList(ctx context.Context, in *pb.ListPipelineReq) (*pb.ListPipelineResp, error) {
	l := executionservicelogic.NewPipelineListLogic(ctx, s.svcCtx)
	return l.PipelineList(in)
}

func (s *ExecutionServiceServer) PipelinePreview(ctx context.Context, in *pb.GetPipelineReq) (*pb.PipelinePreviewResp, error) {
	l := executionservicelogic.NewPipelinePreviewLogic(ctx, s.svcCtx)
	return l.PipelinePreview(in)
}

func (s *ExecutionServiceServer) TektonRuntimeResourceList(ctx context.Context, in *pb.ListTektonRuntimeResourceReq) (*pb.ListTektonRuntimeResourceResp, error) {
	l := executionservicelogic.NewTektonRuntimeResourceListLogic(ctx, s.svcCtx)
	return l.TektonRuntimeResourceList(in)
}

func (s *ExecutionServiceServer) PipelineRun(ctx context.Context, in *pb.RunPipelineReq) (*pb.IdResp, error) {
	l := executionservicelogic.NewPipelineRunLogic(ctx, s.svcCtx)
	return l.PipelineRun(in)
}

func (s *ExecutionServiceServer) PipelineRunStop(ctx context.Context, in *pb.StopPipelineRunReq) (*pb.EmptyResp, error) {
	l := executionservicelogic.NewPipelineRunStopLogic(ctx, s.svcCtx)
	return l.PipelineRunStop(in)
}

func (s *ExecutionServiceServer) PipelineRunDelete(ctx context.Context, in *pb.DeletePipelineRunReq) (*pb.EmptyResp, error) {
	l := executionservicelogic.NewPipelineRunDeleteLogic(ctx, s.svcCtx)
	return l.PipelineRunDelete(in)
}

func (s *ExecutionServiceServer) PipelineRunList(ctx context.Context, in *pb.ListPipelineRunReq) (*pb.ListPipelineRunResp, error) {
	l := executionservicelogic.NewPipelineRunListLogic(ctx, s.svcCtx)
	return l.PipelineRunList(in)
}

func (s *ExecutionServiceServer) PipelineRunStageList(ctx context.Context, in *pb.ListPipelineRunStageReq) (*pb.ListPipelineRunStageResp, error) {
	l := executionservicelogic.NewPipelineRunStageListLogic(ctx, s.svcCtx)
	return l.PipelineRunStageList(in)
}

func (s *ExecutionServiceServer) PipelineRunLog(ctx context.Context, in *pb.PipelineRunLogReq) (*pb.PipelineRunLogResp, error) {
	l := executionservicelogic.NewPipelineRunLogLogic(ctx, s.svcCtx)
	return l.PipelineRunLog(in)
}

func (s *ExecutionServiceServer) PipelineRunYamlSnapshot(ctx context.Context, in *pb.PipelineRunYamlSnapshotReq) (*pb.PipelineRunYamlSnapshotResp, error) {
	l := executionservicelogic.NewPipelineRunYamlSnapshotLogic(ctx, s.svcCtx)
	return l.PipelineRunYamlSnapshot(in)
}

func (s *ExecutionServiceServer) PipelineRunArtifactList(ctx context.Context, in *pb.PipelineRunArtifactListReq) (*pb.PipelineRunArtifactListResp, error) {
	l := executionservicelogic.NewPipelineRunArtifactListLogic(ctx, s.svcCtx)
	return l.PipelineRunArtifactList(in)
}

func (s *ExecutionServiceServer) PipelineRunInputList(ctx context.Context, in *pb.PipelineRunInputListReq) (*pb.PipelineRunInputListResp, error) {
	l := executionservicelogic.NewPipelineRunInputListLogic(ctx, s.svcCtx)
	return l.PipelineRunInputList(in)
}

func (s *ExecutionServiceServer) PipelineRunInputProceed(ctx context.Context, in *pb.PipelineRunInputActionReq) (*pb.EmptyResp, error) {
	l := executionservicelogic.NewPipelineRunInputProceedLogic(ctx, s.svcCtx)
	return l.PipelineRunInputProceed(in)
}

func (s *ExecutionServiceServer) PipelineRunInputAbort(ctx context.Context, in *pb.PipelineRunInputActionReq) (*pb.EmptyResp, error) {
	l := executionservicelogic.NewPipelineRunInputAbortLogic(ctx, s.svcCtx)
	return l.PipelineRunInputAbort(in)
}

func (s *ExecutionServiceServer) PipelineDashboard(ctx context.Context, in *pb.PipelineDashboardReq) (*pb.PipelineDashboardResp, error) {
	l := executionservicelogic.NewPipelineDashboardLogic(ctx, s.svcCtx)
	return l.PipelineDashboard(in)
}

func (s *ExecutionServiceServer) JenkinsAgentList(ctx context.Context, in *pb.JenkinsAgentListReq) (*pb.JenkinsAgentListResp, error) {
	l := executionservicelogic.NewJenkinsAgentListLogic(ctx, s.svcCtx)
	return l.JenkinsAgentList(in)
}
