// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	containerRegistryFieldNames          = builder.RawFieldNames(&ContainerRegistry{})
	containerRegistryRows                = strings.Join(containerRegistryFieldNames, ",")
	containerRegistryRowsExpectAutoSet   = strings.Join(stringx.Remove(containerRegistryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	containerRegistryRowsWithPlaceHolder = strings.Join(stringx.Remove(containerRegistryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsContainerRegistryIdPrefix   = "cache:ikubeops:containerRegistry:id:"
	cacheIkubeopsContainerRegistryUuidPrefix = "cache:ikubeops:containerRegistry:uuid:"
)

type (
	containerRegistryModel interface {
		Insert(ctx context.Context, data *ContainerRegistry) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*ContainerRegistry, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*ContainerRegistry, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*ContainerRegistry, error)
		FindOneByUuid(ctx context.Context, uuid string) (*ContainerRegistry, error)
		Update(ctx context.Context, data *ContainerRegistry) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultContainerRegistryModel struct {
		sqlc.CachedConn
		table string
	}

	ContainerRegistry struct {
		Id          uint64         `db:"id"`          // 主键
		Name        string         `db:"name"`        // 仓库名称
		Uuid        string         `db:"uuid"`        // 仓库唯一标识
		Type        string         `db:"type"`        // 仓库类型: harbor, docker-registry, nexus
		Env         string         `db:"env"`         // 环境标识: dev, test, staging, prod
		Url         string         `db:"url"`         // 仓库地址，如: https://harbor.example.com
		Username    string         `db:"username"`    // 仓库访问用户名
		Password    string         `db:"password"`    // 仓库访问密码（建议加密存储）
		Insecure    int64          `db:"insecure"`    // 是否跳过证书验证: 0-否, 1-是
		CaCert      sql.NullString `db:"ca_cert"`     // CA 证书内容
		Config      sql.NullString `db:"config"`      // 扩展配置（JSON 格式），不同类型仓库的特殊配置
		Status      int64          `db:"status"`      // 仓库状态: 0-禁用, 1-启用
		Description string         `db:"description"` // 仓库描述
		CreatedBy   string         `db:"created_by"`  // 创建人
		UpdatedBy   string         `db:"updated_by"`  // 更新人
		CreatedAt   time.Time      `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`  // 更新时间
		IsDeleted   int64          `db:"is_deleted"`  // 删除标记: 0-未删除, 1-已删除
	}
)

func newContainerRegistryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultContainerRegistryModel {
	return &defaultContainerRegistryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`container_registry`",
	}
}

func (m *defaultContainerRegistryModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, id)
	ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, data.Uuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsContainerRegistryIdKey, ikubeopsContainerRegistryUuidKey)
	return err
}

func (m *defaultContainerRegistryModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, id)
	ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, data.Uuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsContainerRegistryIdKey, ikubeopsContainerRegistryUuidKey)
	return err
}

func (m *defaultContainerRegistryModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultContainerRegistryModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, id)
		ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, data.Uuid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsContainerRegistryIdKey, ikubeopsContainerRegistryUuidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultContainerRegistryModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, id)
		ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, data.Uuid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsContainerRegistryIdKey, ikubeopsContainerRegistryUuidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultContainerRegistryModel) FindOne(ctx context.Context, id uint64) (*ContainerRegistry, error) {
	ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, id)
	var resp ContainerRegistry
	err := m.QueryRowCtx(ctx, &resp, ikubeopsContainerRegistryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", containerRegistryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContainerRegistryModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*ContainerRegistry, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*ContainerRegistry
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", containerRegistryRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultContainerRegistryModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*ContainerRegistry, error) {
	// 处理 nil 参数
	if args == nil {
		args = []any{}
	}
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", containerRegistryRows, m.table, where, orderStr)
	var resp []*ContainerRegistry
	// 根据是否有参数来调用
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultContainerRegistryModel) FindOneByUuid(ctx context.Context, uuid string) (*ContainerRegistry, error) {
	ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, uuid)
	var resp ContainerRegistry
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsContainerRegistryUuidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `uuid` = ? AND `is_deleted` = 0  limit 1", containerRegistryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uuid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultContainerRegistryModel) Insert(ctx context.Context, data *ContainerRegistry) (sql.Result, error) {
	ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, data.Id)
	ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, data.Uuid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, containerRegistryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Uuid, data.Type, data.Env, data.Url, data.Username, data.Password, data.Insecure, data.CaCert, data.Config, data.Status, data.Description, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, ikubeopsContainerRegistryIdKey, ikubeopsContainerRegistryUuidKey)
	return ret, err
}

func (m *defaultContainerRegistryModel) Update(ctx context.Context, newData *ContainerRegistry) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsContainerRegistryIdKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, data.Id)
	ikubeopsContainerRegistryUuidKey := fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryUuidPrefix, data.Uuid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, containerRegistryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Uuid, newData.Type, newData.Env, newData.Url, newData.Username, newData.Password, newData.Insecure, newData.CaCert, newData.Config, newData.Status, newData.Description, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, ikubeopsContainerRegistryIdKey, ikubeopsContainerRegistryUuidKey)
	return err
}

func (m *defaultContainerRegistryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsContainerRegistryIdPrefix, primary)
}

func (m *defaultContainerRegistryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", containerRegistryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultContainerRegistryModel) tableName() string {
	return m.table
}
