// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	registryProjectBindingFieldNames          = builder.RawFieldNames(&RegistryProjectBinding{})
	registryProjectBindingRows                = strings.Join(registryProjectBindingFieldNames, ",")
	registryProjectBindingRowsExpectAutoSet   = strings.Join(stringx.Remove(registryProjectBindingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	registryProjectBindingRowsWithPlaceHolder = strings.Join(stringx.Remove(registryProjectBindingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheIkubeopsRegistryProjectBindingIdPrefix                                                 = "cache:ikubeops:registryProjectBinding:id:"
	cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix = "cache:ikubeops:registryProjectBinding:registryId:appProjectId:registryProjectName:isDeleted:"
)

type (
	registryProjectBindingModel interface {
		Insert(ctx context.Context, data *RegistryProjectBinding) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*RegistryProjectBinding, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*RegistryProjectBinding, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*RegistryProjectBinding, error)
		FindOneByRegistryIdAppProjectIdRegistryProjectNameIsDeleted(ctx context.Context, registryId uint64, appProjectId uint64, registryProjectName string, isDeleted int64) (*RegistryProjectBinding, error)
		Update(ctx context.Context, data *RegistryProjectBinding) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultRegistryProjectBindingModel struct {
		sqlc.CachedConn
		table string
	}

	RegistryProjectBinding struct {
		Id                  uint64    `db:"id"`                    // 主键
		RegistryId          uint64    `db:"registry_id"`           // 仓库 ID
		AppProjectId        uint64    `db:"app_project_id"`        // 应用项目 ID
		RegistryProjectName string    `db:"registry_project_name"` // 仓库中的私有项目名称
		RegistryProjectId   string    `db:"registry_project_id"`   // 仓库中的项目 ID（某些仓库类型可能有）
		CreatedAt           time.Time `db:"created_at"`            // 创建时间
		UpdatedAt           time.Time `db:"updated_at"`            // 更新时间
		IsDeleted           int64     `db:"is_deleted"`            // 删除标记: 0-未删除, 1-已删除
	}
)

func newRegistryProjectBindingModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRegistryProjectBindingModel {
	return &defaultRegistryProjectBindingModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`registry_project_binding`",
	}
}

func (m *defaultRegistryProjectBindingModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, id)
	ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.IsDeleted)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsRegistryProjectBindingIdKey, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey)
	return err
}

func (m *defaultRegistryProjectBindingModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, id)
	ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.IsDeleted)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, ikubeopsRegistryProjectBindingIdKey, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey)
	return err
}

func (m *defaultRegistryProjectBindingModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultRegistryProjectBindingModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, id)
		ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.IsDeleted) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, ikubeopsRegistryProjectBindingIdKey, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultRegistryProjectBindingModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, id)
		ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.IsDeleted) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, ikubeopsRegistryProjectBindingIdKey, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultRegistryProjectBindingModel) FindOne(ctx context.Context, id uint64) (*RegistryProjectBinding, error) {
	ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, id)
	var resp RegistryProjectBinding
	err := m.QueryRowCtx(ctx, &resp, ikubeopsRegistryProjectBindingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", registryProjectBindingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRegistryProjectBindingModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*RegistryProjectBinding, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*RegistryProjectBinding
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", registryProjectBindingRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultRegistryProjectBindingModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*RegistryProjectBinding, error) {
	// 处理 nil 参数
	if args == nil {
		args = []any{}
	}
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	// 处理查询条件和参数
	var finalArgs []any
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
		// 只有当有查询条件时才使用参数
		if len(args) > 0 {
			finalArgs = args
		}
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", registryProjectBindingRows, m.table, where, orderStr)
	var resp []*RegistryProjectBinding
	// 根据是否有参数来调用
	var err error
	if len(finalArgs) > 0 {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, finalArgs...)
	} else {
		err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery)
	}
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultRegistryProjectBindingModel) FindOneByRegistryIdAppProjectIdRegistryProjectNameIsDeleted(ctx context.Context, registryId uint64, appProjectId uint64, registryProjectName string, isDeleted int64) (*RegistryProjectBinding, error) {
	ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, registryId, appProjectId, registryProjectName, isDeleted)
	var resp RegistryProjectBinding
	err := m.QueryRowIndexCtx(ctx, &resp, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `registry_id` = ? and `app_project_id` = ? and `registry_project_name` = ? and `is_deleted` = ? AND `is_deleted` = 0  limit 1", registryProjectBindingRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, registryId, appProjectId, registryProjectName, isDeleted); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRegistryProjectBindingModel) Insert(ctx context.Context, data *RegistryProjectBinding) (sql.Result, error) {
	ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, data.Id)
	ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.IsDeleted)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, registryProjectBindingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.RegistryProjectId, data.IsDeleted)
	}, ikubeopsRegistryProjectBindingIdKey, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey)
	return ret, err
}

func (m *defaultRegistryProjectBindingModel) Update(ctx context.Context, newData *RegistryProjectBinding) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	ikubeopsRegistryProjectBindingIdKey := fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, data.Id)
	ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheIkubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedPrefix, data.RegistryId, data.AppProjectId, data.RegistryProjectName, data.IsDeleted)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, registryProjectBindingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RegistryId, newData.AppProjectId, newData.RegistryProjectName, newData.RegistryProjectId, newData.IsDeleted, newData.Id)
	}, ikubeopsRegistryProjectBindingIdKey, ikubeopsRegistryProjectBindingRegistryIdAppProjectIdRegistryProjectNameIsDeletedKey)
	return err
}

func (m *defaultRegistryProjectBindingModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheIkubeopsRegistryProjectBindingIdPrefix, primary)
}

func (m *defaultRegistryProjectBindingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", registryProjectBindingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRegistryProjectBindingModel) tableName() string {
	return m.table
}
